// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	// CreateCashier: Creates a new cashier record
	// Purpose: Add new cashier to the system
	// Parameters:
	//   $1: merchant_id - Associated merchant ID
	//   $2: user_id - User account ID for the cashier
	//   $3: name - Full name of the cashier
	// Returns: Complete created cashier record
	// Business Logic:
	//   - Sets created_at timestamp automatically
	//   - Requires all mandatory fields
	CreateCashier(ctx context.Context, arg CreateCashierParams) (*Cashier, error)
	// DeleteAllPermanentCashiers: Purges all trashed cashiers
	// Purpose: Clean up all soft-deleted records
	// Business Logic:
	//   - Irreversible bulk deletion
	//   - Only affects already soft-deleted records
	//   - Typically used during database maintenance
	DeleteAllPermanentCashiers(ctx context.Context) error
	// DeleteCashierPermanently: Hard-deletes a cashier
	// Purpose: Completely remove cashier from database
	// Parameters:
	//   $1: cashier_id - ID of cashier to delete
	// Business Logic:
	//   - Permanent deletion of already soft-deleted records
	//   - No return value (exec-only)
	//   - Use with caution - irreversible operation
	DeleteCashierPermanently(ctx context.Context, cashierID int32) error
	// GetCashierByID: Retrieves active cashier by ID
	// Purpose: Fetch cashier details for display/editing
	// Parameters:
	//   $1: cashier_id - ID of the cashier to retrieve
	// Returns: Full cashier record if found and active
	// Business Logic:
	//   - Excludes soft-deleted records
	//   - Returns single record or nothing
	GetCashierById(ctx context.Context, cashierID int32) (*Cashier, error)
	// GetCashiers: Retrieves paginated list of active cashiers with search capability
	// Purpose: List all active cashiers for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter cashiers by name (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All cashier fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted cashiers (deleted_at IS NULL)
	//   - Supports partial text matching on name field (case-insensitive)
	//   - Returns newest cashiers first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetCashiers(ctx context.Context, arg GetCashiersParams) ([]*GetCashiersRow, error)
	// GetCashiersActive: Retrieves paginated list of active cashiers with search capability
	// Purpose: List all active cashiers for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter cashiers by name (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All cashier fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted cashiers (deleted_at IS NULL)
	//   - Supports partial text matching on name field (case-insensitive)
	//   - Returns newest cashiers first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetCashiersActive(ctx context.Context, arg GetCashiersActiveParams) ([]*GetCashiersActiveRow, error)
	// GetCashiersByMerchant: Retrieves active cashiers filtered by merchant_id
	// Parameters:
	//   $1: Merchant ID (required)
	//   $2: Search term for cashier name (optional)
	//   $3: Limit
	//   $4: Offset
	// Returns:
	//   Cashier records belonging to specified merchant with total_count
	GetCashiersByMerchant(ctx context.Context, arg GetCashiersByMerchantParams) ([]*GetCashiersByMerchantRow, error)
	// GetCashiersTrashed: Retrieves paginated list of soft-deleted cashiers with search capability
	// Purpose: List all trashed (soft-deleted) cashiers for recovery or audit purposes
	// Parameters:
	//   $1: search_term - Optional text to filter cashiers by name (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All cashier fields plus total_count of matching records
	// Business Logic:
	//   - Includes only soft-deleted cashiers (deleted_at IS NOT NULL)
	//   - Supports partial text matching on name field (case-insensitive)
	//   - Returns newest deleted cashiers first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetCashiersTrashed(ctx context.Context, arg GetCashiersTrashedParams) ([]*GetCashiersTrashedRow, error)
	// GetMonthlyCashier: Retrieves monthly sales activity for all cashiers within a 1-year period
	// Purpose: Provides cashier performance metrics by month for operational analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	// Returns:
	//   cashier_id: Unique identifier for the cashier
	//   cashier_name: Full name of the cashier
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   order_count: Number of orders processed
	//   total_sales: Gross sales amount generated
	// Business Logic:
	//   - Analyzes a rolling 12-month period from the reference date
	//   - Excludes deleted records to maintain data integrity
	//   - Groups results by cashier and month for granular performance tracking
	//   - Uses abbreviated month names for compact visual reporting
	//   - Orders chronologically for trend analysis
	GetMonthlyCashier(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyCashierRow, error)
	// GetMonthlyCashierByCashierId: Retrieves monthly sales activity for all cashiers within a 1-year period by cashier id
	// Purpose: Provides cashier performance metrics by month for operational analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	//   $2: Reference cashier_id
	// Returns:
	//   cashier_id: Unique identifier for the cashier
	//   cashier_name: Full name of the cashier
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   order_count: Number of orders processed
	//   total_sales: Gross sales amount generated
	// Business Logic:
	//   - Analyzes a rolling 12-month period from the reference date
	//   - Excludes deleted records to maintain data integrity
	//   - Groups results by cashier and month for granular performance tracking
	//   - Uses abbreviated month names for compact visual reporting
	//   - Orders chronologically for trend analysis
	GetMonthlyCashierByCashierId(ctx context.Context, arg GetMonthlyCashierByCashierIdParams) ([]*GetMonthlyCashierByCashierIdRow, error)
	// GetMonthlyCashierByMerchant: Retrieves monthly sales activity for all cashiers within a 1-year period by merchant id
	// Purpose: Provides cashier performance metrics by month for operational analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	//   $2: Reference merchant_id
	// Returns:
	//   cashier_id: Unique identifier for the cashier
	//   cashier_name: Full name of the cashier
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   order_count: Number of orders processed
	//   total_sales: Gross sales amount generated
	// Business Logic:
	//   - Analyzes a rolling 12-month period from the reference date
	//   - Excludes deleted records to maintain data integrity
	//   - Groups results by cashier and month for granular performance tracking
	//   - Uses abbreviated month names for compact visual reporting
	//   - Orders chronologically for trend analysis
	GetMonthlyCashierByMerchant(ctx context.Context, arg GetMonthlyCashierByMerchantParams) ([]*GetMonthlyCashierByMerchantRow, error)
	// GetMonthlyTotalSalesById: Retrieves monthly sales totals filtered by cashier ID
	// Purpose: Provides monthly sales analytics for a specific merchant across two time periods
	// Parameters:
	//   $1: Start date of first comparison period
	//   $2: End date of first comparison period
	//   $3: Start date of second comparison period
	//   $4: End date of second comparison period
	//   $5: Cashier ID to filter by
	// Returns:
	//   year: Year of sales data (text format)
	//   month_name: Full month name (e.g. "January")
	//   total_sales: Sum of order totals for that month (0 if no sales)
	// Business Logic:
	//   - Compares sales between two customizable time windows (e.g. this month vs last month)
	//   - Ensures all months appear in results even with no sales (gap filling)
	//   - Only includes active/non-deleted orders and cashiers
	//   - Formats output for easy display in reports/dashboards
	GetMonthlyTotalSalesById(ctx context.Context, arg GetMonthlyTotalSalesByIdParams) ([]*GetMonthlyTotalSalesByIdRow, error)
	// GetMonthlyTotalSalesByMerchant: Retrieves monthly sales totals filtered by merchant ID
	// Purpose: Provides monthly sales analytics for a specific merchant across two time periods
	// Parameters:
	//   $1: Start date of first comparison period
	//   $2: End date of first comparison period
	//   $3: Start date of second comparison period
	//   $4: End date of second comparison period
	//   $5: Merchant ID to filter by
	// Returns:
	//   year: Year of sales data (text format)
	//   month_name: Full month name (e.g. "January")
	//   total_sales: Sum of order totals for that month (0 if no sales)
	// Business Logic:
	//   - Compares sales between two customizable time windows (e.g. this month vs last month)
	//   - Ensures all months appear in results even with no sales (gap filling)
	//   - Only includes active/non-deleted orders and cashiers
	//   - Formats output for easy display in reports/dashboards
	GetMonthlyTotalSalesByMerchant(ctx context.Context, arg GetMonthlyTotalSalesByMerchantParams) ([]*GetMonthlyTotalSalesByMerchantRow, error)
	// GetMonthlyTotalSalesCashier: Retrieves monthly sales totals for cashiers across two date ranges
	// Purpose: Compare sales performance between two time periods (typically current vs previous period)
	// Parameters:
	//   $1: Start date of first period
	//   $2: End date of first period
	//   $3: Start date of second period
	//   $4: End date of second period
	// Returns:
	//   year: The year of the sales data
	//   month_name: The full month name (e.g., "January")
	//   total_sales: Sum of order totals for that month (0 if no sales)
	// Business Logic:
	//   - Compares sales between two customizable time windows (e.g. this month vs last month)
	//   - Ensures all months appear in results even with no sales (gap filling)
	//   - Only includes active/non-deleted orders and cashiers
	//   - Formats output for easy display in reports/dashboards
	GetMonthlyTotalSalesCashier(ctx context.Context, arg GetMonthlyTotalSalesCashierParams) ([]*GetMonthlyTotalSalesCashierRow, error)
	// GetYearlyCashier: Retrieves annual sales performance for cashiers over 5-year span
	// Purpose: Enables long-term cashier productivity trend analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	// Returns:
	//   year: 4-digit year as text
	//   cashier_id: Unique cashier identifier
	//   cashier_name: Full name of the cashier
	//   order_count: Annual transaction volume
	//   total_sales: Yearly revenue generated
	// Business Logic:
	//   - Covers current year plus previous 4 years (5-year total window)
	//   - Maintains data quality by excluding soft-deleted records
	//   - Provides both quantitative (order count) and financial (sales) metrics
	//   - Orders results chronologically then by cashier for consistent reporting
	//   - Designed for workforce planning and incentive calculations
	GetYearlyCashier(ctx context.Context, dollar_1 time.Time) ([]*GetYearlyCashierRow, error)
	// GetYearlyCashierByCashierId: Retrieves annual sales performance for cashiers over 5-year span by cashier id
	// Purpose: Enables long-term cashier productivity trend analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	//   $2: Reference cashier_id
	// Returns:
	//   year: 4-digit year as text
	//   cashier_id: Unique cashier identifier
	//   cashier_name: Full name of the cashier
	//   order_count: Annual transaction volume
	//   total_sales: Yearly revenue generated
	// Business Logic:
	//   - Covers current year plus previous 4 years (5-year total window)
	//   - Maintains data quality by excluding soft-deleted records
	//   - Provides both quantitative (order count) and financial (sales) metrics
	//   - Orders results chronologically then by cashier for consistent reporting
	//   - Designed for workforce planning and incentive calculations
	GetYearlyCashierByCashierId(ctx context.Context, arg GetYearlyCashierByCashierIdParams) ([]*GetYearlyCashierByCashierIdRow, error)
	// GetYearlyCashierByMerchant: Retrieves annual sales performance for cashiers over 5-year span by merchant id
	// Purpose: Enables long-term cashier productivity trend analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	//   $2: Reference cashier_id
	// Returns:
	//   year: 4-digit year as text
	//   cashier_id: Unique cashier identifier
	//   cashier_name: Full name of the cashier
	//   order_count: Annual transaction volume
	//   total_sales: Yearly revenue generated
	// Business Logic:
	//   - Covers current year plus previous 4 years (5-year total window)
	//   - Maintains data quality by excluding soft-deleted records
	//   - Provides both quantitative (order count) and financial (sales) metrics
	//   - Orders results chronologically then by cashier for consistent reporting
	//   - Designed for workforce planning and incentive calculations
	GetYearlyCashierByMerchant(ctx context.Context, arg GetYearlyCashierByMerchantParams) ([]*GetYearlyCashierByMerchantRow, error)
	// GetYearlyTotalSalesById: Retrieves yearly sales totals filtered by cashier ID
	// Purpose: Provides year-over-year sales comparison for a specific cashier
	// Parameters:
	//   $1: Current year to analyze (integer)
	//   $2: Merchant ID to filter by
	// Returns:
	//   year: Year as text
	//   total_sales: Annual sales total (0 if no sales)
	// Business Logic:
	//   - Automatically compares current year with previous year
	//   - Includes zero-value years for complete reporting
	//   - Filters by cashier while maintaining data integrity
	GetYearlyTotalSalesById(ctx context.Context, arg GetYearlyTotalSalesByIdParams) ([]*GetYearlyTotalSalesByIdRow, error)
	// GetYearlyTotalSalesByMerchant: Retrieves yearly sales totals filtered by merchant ID
	// Purpose: Provides year-over-year sales comparison for a specific merchant
	// Parameters:
	//   $1: Current year to analyze (integer)
	//   $2: Merchant ID to filter by
	// Returns:
	//   year: Year as text
	//   total_sales: Annual sales total (0 if no sales)
	// Business Logic:
	//   - Automatically compares current year with previous year
	//   - Includes zero-value years for complete reporting
	//   - Filters by merchant while maintaining data integrity
	GetYearlyTotalSalesByMerchant(ctx context.Context, arg GetYearlyTotalSalesByMerchantParams) ([]*GetYearlyTotalSalesByMerchantRow, error)
	// GetYearlyTotalSalesCashier: Retrieves yearly sales totals for cashiers across current and previous year
	// Purpose: Year-over-year sales comparison
	// Parameters:
	//   $1: The current year (integer)
	// Returns:
	//   year: The year as text
	//   total_sales: Sum of order totals for that year (0 if no sales)
	// Business Logic:
	//   - Automatically compares current year with previous year
	//   - Includes zero-value years for complete reporting
	//   - Filters by merchant while maintaining data integrity
	GetYearlyTotalSalesCashier(ctx context.Context, dollar_1 int32) ([]*GetYearlyTotalSalesCashierRow, error)
	// RestoreAllCashiers: Mass restoration of deleted cashiers
	// Purpose: Recover all trashed cashiers at once
	// Business Logic:
	//   - Reactivates all soft-deleted cashiers
	//   - No parameters needed
	//   - Useful for system recovery scenarios
	RestoreAllCashiers(ctx context.Context) error
	// RestoreCashier: Recovers a soft-deleted cashier
	// Purpose: Reactivate a previously trashed cashier
	// Parameters:
	//   $1: cashier_id - ID of cashier to restore
	// Returns: The restored cashier record
	// Business Logic:
	//   - Nullifies the deleted_at field
	//   - Only works on previously deleted records
	//   - Maintains all original data
	RestoreCashier(ctx context.Context, cashierID int32) (*Cashier, error)
	// TrashCashier: Soft-deletes a cashier record
	// Purpose: Remove cashier from active use without permanent deletion
	// Parameters:
	//   $1: cashier_id - ID of cashier to deactivate
	// Returns: The soft-deleted cashier record
	// Business Logic:
	//   - Sets deleted_at timestamp to current time
	//   - Only works on currently active records
	//   - Allows for recovery via restore function
	TrashCashier(ctx context.Context, cashierID int32) (*Cashier, error)
	// UpdateCashier: Modifies cashier information
	// Purpose: Update cashier details
	// Parameters:
	//   $1: cashier_id - ID of cashier to update
	//   $2: name - New name value
	// Returns: Updated cashier record
	// Business Logic:
	//   - Automatically updates updated_at timestamp
	//   - Only affects active (non-deleted) records
	//   - Returns the modified record for confirmation
	UpdateCashier(ctx context.Context, arg UpdateCashierParams) (*Cashier, error)
}

var _ Querier = (*Queries)(nil)
