// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	RefreshTokenID int32            `json:"refresh_token_id"`
	UserID         int32            `json:"user_id"`
	Token          string           `json:"token"`
	Expiration     time.Time        `json:"expiration"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type ResetToken struct {
	ID         int32     `json:"id"`
	UserID     int64     `json:"user_id"`
	Token      string    `json:"token"`
	ExpiryDate time.Time `json:"expiry_date"`
}

type Role struct {
	RoleID    int32            `json:"role_id"`
	RoleName  string           `json:"role_name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type User struct {
	UserID           int32            `json:"user_id"`
	Firstname        string           `json:"firstname"`
	Lastname         string           `json:"lastname"`
	Email            string           `json:"email"`
	Password         string           `json:"password"`
	VerificationCode string           `json:"verification_code"`
	IsVerified       *bool            `json:"is_verified"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}

type UserRole struct {
	UserRoleID int32            `json:"user_role_id"`
	UserID     int32            `json:"user_id"`
	RoleID     int32            `json:"role_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}
