// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	// CalculateTotalPrice: Calculates total price of active order items for a specific order
	// Purpose: Provides the aggregated monetary value of an order
	// Parameters:
	//   $1: order_id - identifier of the order
	// Returns:
	//   total_price: Sum of (quantity * price) for all active items in the order
	// Business Logic:
	//   - Ignores soft-deleted items
	//   - Ensures result is zero if no items exist
	CalculateTotalPrice(ctx context.Context, orderID int32) (int32, error)
	// CreateOrder: Creates a new order record
	// Purpose: Register a new transaction in the system
	// Parameters:
	//   $1: merchant_id - UUID of the merchant associated with the order
	//   $2: cashier_id - ID of the cashier processing the order
	//   $3: total_price - Numeric total amount of the order
	// Returns: The complete created order record
	// Business Logic:
	//   - Automatically sets created_at timestamp
	//   - Requires merchant_id, cashier_id and total_price
	//   - Typically followed by order item creation
	CreateOrder(ctx context.Context, arg CreateOrderParams) (*Order, error)
	// CreateOrderItem: Inserts a new order item record
	// Purpose: Adds a product to a specific order
	// Parameters:
	//   $1: order_id
	//   $2: product_id
	//   $3: quantity
	//   $4: price
	// Returns:
	//   The newly created order item
	// Business Logic:
	//   - Assumes quantity and price are validated in application layer
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (*OrderItem, error)
	// CreateProduct: Creates a new product record
	// Purpose: Add a new product to inventory
	// Parameters:
	//   $1: merchant_id - Merchant who owns the product
	//   $2: category_id - Product category
	//   $3: name - Product name
	//   $4: description - Detailed description
	//   $5: price - Selling price
	//   $6: count_in_stock - Inventory quantity
	//   $7: brand - Manufacturer brand
	//   $8: weight - Product weight
	//   $9: slug_product - URL-friendly identifier
	//   $10: image_product - Image URL/path
	//   $11: barcode - Product barcode
	// Returns: Complete created product record
	// Business Logic:
	//   - Sets created_at automatically
	//   - Validates required fields
	//   - Initializes inventory tracking
	CreateProduct(ctx context.Context, arg CreateProductParams) (*Product, error)
	// DecrementProductCountStock: Atomically decrements product stock
	// Purpose: Safe inventory decrement with optimistic concurrency guard
	// Parameters:
	//   $1: product_id - Product to update
	//   $2: quantity - Amount to subtract from current stock
	// Returns: Updated product record
	// Business Logic:
	//   - Atomic decrement (no lost update between read and write)
	//   - Refuses to go below zero: WHERE count_in_stock >= $2
	//   - Returns zero rows when stock is insufficient (caller maps to 400)
	DecrementProductCountStock(ctx context.Context, arg DecrementProductCountStockParams) (*Product, error)
	// DeleteAllPermanentOrders: Purges all cancelled orders
	// Purpose: Clean up all soft-deleted order records
	// Business Logic:
	//   - Irreversible bulk deletion operation
	//   - Only affects already cancelled orders
	//   - Typically used during database maintenance
	//   - Should be restricted to admin users
	DeleteAllPermanentOrders(ctx context.Context) (pgconn.CommandTag, error)
	// DeleteAllPermanentOrdersItem: Permanently deletes all trashed order items
	// Purpose: Performs hard delete of all soft-deleted items
	// Parameters: None
	// Returns: None
	// Business Logic:
	//   - Used for data cleanup or archival enforcement
	DeleteAllPermanentOrdersItem(ctx context.Context) error
	// DeleteAllPermanentProducts: Purges all trashed products
	// Purpose: Clean up deleted products
	// Business Logic:
	//   - Bulk permanent deletion
	//   - Database maintenance operation
	DeleteAllPermanentProducts(ctx context.Context) error
	// DeleteOrder: Removes an active order during failed order compensation
	DeleteOrder(ctx context.Context, orderID int32) error
	// DeleteOrderItem: Deletes an active order item during failed order compensation
	DeleteOrderItem(ctx context.Context, orderItemID int32) error
	// DeleteOrderItemPermanently: Permanently deletes a trashed order item
	// Purpose: Removes the record entirely from the database
	// Parameters:
	//   $1: order_item_id
	// Returns: None
	// Business Logic:
	//   - Only deletes if already soft-deleted
	//   - Irreversible action
	DeleteOrderItemPermanently(ctx context.Context, orderItemID int32) error
	// DeleteOrderItemsByOrder: Permanently deletes all items belonging to an order
	DeleteOrderItemsByOrder(ctx context.Context, orderID int32) error
	// DeleteOrderPermanently: Hard-deletes an order
	// Purpose: Completely remove order from database
	// Parameters:
	//   $1: order_id - UUID of order to delete
	// Business Logic:
	//   - Permanent deletion of already cancelled orders
	//   - No return value (exec-only operation)
	//   - Irreversible action - use with caution
	//   - Should trigger deletion of related order_items
	DeleteOrderPermanently(ctx context.Context, orderID int32) (*DeleteOrderPermanentlyRow, error)
	// DeleteProductPermanently: Hard-deletes a product
	// Purpose: Completely remove product record
	// Parameters:
	//   $1: product_id - Product to delete
	// Business Logic:
	//   - Permanent deletion
	//   - Only affects already trashed products
	//   - Irreversible operation
	DeleteProductPermanently(ctx context.Context, productID int32) error
	// GetAllOrdersTrashed: Retrieves all soft-deleted orders for per-order restoration
	GetAllOrdersTrashed(ctx context.Context) ([]*Order, error)
	// GetMonthlyOrder: Retrieves monthly order summary within a 1-year period
	// Purpose: Provides monthly sales performance metrics for trend and operational analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis window
	// Returns:
	//   month: 3-letter abbreviation of the month (e.g., 'Jan')
	//   order_count: Total number of orders in the month
	//   total_revenue: Sum of total price from all orders
	//   total_items_sold: Total quantity of items sold in that month
	// Business Logic:
	//   - Analyzes a 12-month period starting from the month of the reference date
	//   - Ignores soft-deleted records for accurate reporting
	//   - Aggregates data by month for visualizations and monthly performance tracking
	//   - Uses short month format for dashboard/chart compactness
	//   - Sorts chronologically by month
	GetMonthlyOrder(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyOrderRow, error)
	// GetMonthlyOrderByMerchant: Retrieves monthly order summary within a 1-year period by merchant_id
	// Purpose: Provides monthly sales performance metrics for trend and operational analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis window
	//   $2: Merchant ID
	// Returns:
	//   month: 3-letter abbreviation of the month (e.g., 'Jan')
	//   order_count: Total number of orders in the month
	//   total_revenue: Sum of total price from all orders
	//   total_items_sold: Total quantity of items sold in that month
	// Business Logic:
	//   - Analyzes a 12-month period starting from the month of the reference date
	//   - Ignores soft-deleted records for accurate reporting
	//   - Aggregates data by month for visualizations and monthly performance tracking
	//   - Uses short month format for dashboard/chart compactness
	//   - Sorts chronologically by month
	GetMonthlyOrderByMerchant(ctx context.Context, arg GetMonthlyOrderByMerchantParams) ([]*GetMonthlyOrderByMerchantRow, error)
	// GetMonthlyTotalRevenue: Retrieves monthly total revenue across two custom date ranges
	// Purpose: Compare total revenue between two time periods (e.g., current month vs previous month)
	// Parameters:
	//   $1: Start date of first period
	//   $2: End date of first period
	//   $3: Start date of second period
	//   $4: End date of second period
	// Returns:
	//   year: The year of the revenue data
	//   month: The full month name (e.g., "January")
	//   total_revenue: Total revenue (SUM of order totals) for that month (0 if no revenue)
	// Business Logic:
	//   - Compares revenue between two customizable time periods
	//   - Ensures all selected months appear even if no revenue (gap filling)
	//   - Includes only non-deleted orders and order items
	//   - Output formatted for charting or reporting tools
	GetMonthlyTotalRevenue(ctx context.Context, arg GetMonthlyTotalRevenueParams) ([]*GetMonthlyTotalRevenueRow, error)
	// GetMonthlyTotalRevenueById: Retrieves monthly total revenue across two custom date ranges by order_id
	// Purpose: Compare total revenue between two time periods (e.g., current month vs previous month)
	// Parameters:
	//   $1: Start date of first period
	//   $2: End date of first period
	//   $3: Start date of second period
	//   $4: End date of second period
	//   $5: Order ID
	// Returns:
	//   year: The year of the revenue data
	//   month: The full month name (e.g., "January")
	//   total_revenue: Total revenue (SUM of order totals) for that month (0 if no revenue)
	// Business Logic:
	//   - Compares revenue between two customizable time periods
	//   - Ensures all selected months appear even if no revenue (gap filling)
	//   - Includes only non-deleted orders and order items
	//   - Output formatted for charting or reporting tools
	GetMonthlyTotalRevenueById(ctx context.Context, arg GetMonthlyTotalRevenueByIdParams) ([]*GetMonthlyTotalRevenueByIdRow, error)
	// GetMonthlyTotalRevenueByMerchant: Retrieves monthly total revenue across two custom date ranges by merchant_id
	// Purpose: Compare total revenue between two time periods (e.g., current month vs previous month)
	// Parameters:
	//   $1: Start date of first period
	//   $2: End date of first period
	//   $3: Start date of second period
	//   $4: End date of second period
	//   $5: Order ID
	// Returns:
	//   year: The year of the revenue data
	//   month: The full month name (e.g., "January")
	//   total_revenue: Total revenue (SUM of order totals) for that month (0 if no revenue)
	// Business Logic:
	//   - Compares revenue between two customizable time periods
	//   - Ensures all selected months appear even if no revenue (gap filling)
	//   - Includes only non-deleted orders and order items
	//   - Output formatted for charting or reporting tools
	GetMonthlyTotalRevenueByMerchant(ctx context.Context, arg GetMonthlyTotalRevenueByMerchantParams) ([]*GetMonthlyTotalRevenueByMerchantRow, error)
	// GetOrderByID: Retrieves an active order by ID
	// Purpose: Fetch order details for display/processing
	// Parameters:
	//   $1: order_id - UUID of the order to retrieve
	// Returns: Full order record if found and active
	// Business Logic:
	//   - Excludes soft-deleted orders
	//   - Used for order viewing, receipts, and processing
	//   - Typically joined with order_items in application
	GetOrderByID(ctx context.Context, orderID int32) (*Order, error)
	// GetOrderByIDTrashed: Retrieves an order regardless of soft-delete state
	GetOrderByIDTrashed(ctx context.Context, orderID int32) (*Order, error)
	// GetOrderItems: Retrieves active order items with pagination and search
	// Purpose: Provides paginated listing of non-deleted order items for display or reporting
	// Parameters:
	//   $1: Search keyword (matches order_id or product_id, optional)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting record index)
	// Returns:
	//   All matching order item fields
	//   total_count: Total number of results ignoring pagination (for frontend pagination UI)
	// Business Logic:
	//   - Filters out soft-deleted items
	//   - Supports keyword-based filtering
	//   - Includes total result count via window function
	GetOrderItems(ctx context.Context, arg GetOrderItemsParams) ([]*GetOrderItemsRow, error)
	// GetOrderItemsActive: Retrieves active order items (duplicate-safe with GetOrderItems)
	// Purpose: Lists active (non-deleted) order items with pagination and optional search
	// Parameters:
	//   $1: Search keyword (order_id or product_id, optional)
	//   $2: Limit (pagination size)
	//   $3: Offset (pagination start)
	// Returns:
	//   Order item fields plus total matching count
	// Business Logic:
	//   - Behaves similarly to GetOrderItems
	//   - Used when clarity between active/trashed context is required
	GetOrderItemsActive(ctx context.Context, arg GetOrderItemsActiveParams) ([]*GetOrderItemsActiveRow, error)
	// GetOrderItemsByOrder: Retrieves active order items for a specific order
	// Purpose: Fetches all non-deleted order items under one order
	// Parameters:
	//   $1: order_id
	// Returns:
	//   List of active order items
	// Business Logic:
	//   - Excludes soft-deleted entries
	GetOrderItemsByOrder(ctx context.Context, orderID int32) ([]*OrderItem, error)
	// GetOrderItemsTrashed: Retrieves soft-deleted order items with pagination
	// Purpose: Allows review and management of trashed order items
	// Parameters:
	//   $1: Search keyword (order_id or product_id, optional)
	//   $2: Limit (number of rows per page)
	//   $3: Offset (starting point for pagination)
	// Returns:
	//   All matching deleted order item fields
	//   total_count: Total number of trashed results
	// Business Logic:
	//   - Only includes records with non-null deleted_at (trashed)
	//   - Enables optional keyword search and pagination
	//   - Sorted by deletion date for recent trash activity review
	GetOrderItemsTrashed(ctx context.Context, arg GetOrderItemsTrashedParams) ([]*GetOrderItemsTrashedRow, error)
	// GetOrders: Retrieves paginated list of active orders with search capability
	// Purpose: List all active orders for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter orders by ID or total price (NULL for no filter)
	//   $2: limit - Maximum number of records to return (pagination limit)
	//   $3: offset - Number of records to skip (pagination offset)
	// Returns:
	//   All order fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted orders (deleted_at IS NULL)
	//   - Supports partial text matching on order_id and total_price fields (case-insensitive)
	//   - Returns newest orders first (created_at DESC)
	//   - Provides total_count for client-side pagination
	//   - Uses window function COUNT(*) OVER() for efficient total count
	GetOrders(ctx context.Context, arg GetOrdersParams) ([]*GetOrdersRow, error)
	// GetOrdersActive: Retrieves paginated list of active orders (identical to GetOrders)
	// Purpose: Maintains consistent API pattern with other active/trashed endpoints
	// Parameters:
	//   $1: search_term - Optional filter text for order ID or price
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns:
	//   Active order records with total_count
	// Business Logic:
	//   - Same functionality as GetOrders
	//   - Exists for consistency in API design patterns
	// Note: Could be consolidated with GetOrders if duplicate functionality is undesired
	GetOrdersActive(ctx context.Context, arg GetOrdersActiveParams) ([]*GetOrdersActiveRow, error)
	// GetOrdersByMerchant: Retrieves merchant-specific orders with pagination
	// Purpose: List orders filtered by merchant ID
	// Parameters:
	//   $1: search_term - Optional text to filter orders
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	//   $4: merchant_id - Optional merchant UUID to filter by (NULL for all merchants)
	// Returns:
	//   Order records with total_count
	// Business Logic:
	//   - Combines merchant filtering with search functionality
	//   - Maintains same sorting and pagination as other order queries
	//   - Useful for merchant-specific order dashboards
	//   - NULL merchant_id parameter returns all merchants' orders
	GetOrdersByMerchant(ctx context.Context, arg GetOrdersByMerchantParams) ([]*GetOrdersByMerchantRow, error)
	// GetOrdersTrashed: Retrieves paginated list of soft-deleted orders
	// Purpose: View and manage deleted orders for potential restoration
	// Parameters:
	//   $1: search_term - Optional text to filter trashed orders
	//   $2: limit - Maximum records per page
	//   $3: offset - Records to skip
	// Returns:
	//   Trashed order records with total_count
	// Business Logic:
	//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
	//   - Maintains same search functionality as active order queries
	//   - Preserves chronological sorting (newest first)
	//   - Used in order recovery/audit interfaces
	//   - Includes total_count for pagination in trash management UI
	GetOrdersTrashed(ctx context.Context, arg GetOrdersTrashedParams) ([]*GetOrdersTrashedRow, error)
	// GetProductByID: Retrieves active product by ID
	// Purpose: Fetch product details for display/purchase
	// Parameters:
	//   $1: product_id - ID of product to retrieve
	// Returns: Full product record if active
	// Business Logic:
	//   - Excludes deleted products
	//   - Used for product pages and checkout
	GetProductByID(ctx context.Context, productID int32) (*Product, error)
	// GetProductByIdTrashed: Retrieves product including deleted
	// Purpose: View deleted products for restoration
	// Parameters:
	//   $1: product_id - ID of product to retrieve
	// Returns: Product record regardless of deletion status
	// Business Logic:
	//   - Bypasses deleted_at filter
	//   - Used in admin/recovery interfaces
	GetProductByIdTrashed(ctx context.Context, productID int32) (*Product, error)
	// GetProducts: Retrieves paginated list of active products with search capability
	// Purpose: List all active (non-deleted) products for display in UI
	// Parameters:
	//   $1: search_term - Optional text to filter products (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All product fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted products (deleted_at IS NULL)
	//   - Supports partial, case-insensitive search on name, description, brand, slug, and barcode
	//   - Orders results by newest first (created_at DESC)
	//   - Uses COUNT(*) OVER() to include total matching record count for pagination UI
	GetProducts(ctx context.Context, arg GetProductsParams) ([]*GetProductsRow, error)
	// GetProductsActive: Retrieves paginated list of active products (duplicate of GetProducts)
	// Purpose: Explicitly return active (non-deleted) products with search capability
	// Parameters:
	//   $1: search_term - Optional text to filter products (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All product fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted products (deleted_at IS NULL)
	//   - Supports partial, case-insensitive search on name, description, brand, slug, and barcode
	//   - Ordered by newest first (created_at DESC)
	//   - Useful if frontend/backend wants clearer distinction in naming
	GetProductsActive(ctx context.Context, arg GetProductsActiveParams) ([]*GetProductsActiveRow, error)
	// GetProductsByCategoryName: Retrieves paginated and filtered products under a specific category name
	// Purpose: Display products by category for customers or category-focused pages
	// Parameters:
	//   $1: category_name - The name of the category to filter by
	//   $2: search_term - Optional text to filter by product name or description
	//   $3: min_price - Minimum price filter (0 to ignore)
	//   $4: max_price - Maximum price filter (0 to ignore, defaults to very high value)
	//   $5: limit - Number of products to return (pagination)
	//   $6: offset - Number of products to skip (pagination)
	// Returns:
	//   - Filtered list of product fields including category name
	//   - total_count of all matching products for pagination UI
	// Business Logic:
	//   - Excludes soft-deleted products (deleted_at IS NULL)
	//   - Matches category name exactly
	//   - Supports case-insensitive partial search on name and description
	//   - Filters by category ID only if provided
	//   - Filters by price range only if values provided
	//   - Ordered by newest products first (created_at DESC)
	GetProductsByCategoryName(ctx context.Context, arg GetProductsByCategoryNameParams) ([]*GetProductsByCategoryNameRow, error)
	// GetProductsByMerchant: Retrieves paginated and filtered products owned by a specific merchant
	// Purpose: Allow merchants to view and manage their own products with advanced filtering options
	// Parameters:
	//   $1: merchant_id - Filter products belonging to this merchant
	//   $2: search_term - Optional text to filter by product name or description
	//   $3: category_id - Optional category filter (0 or NULL to ignore)
	//   $4: min_price - Minimum price filter (0 to ignore)
	//   $5: max_price - Maximum price filter (0 to ignore, defaults to very high value)
	//   $6: limit - Number of products to return (pagination)
	//   $7: offset - Number of products to skip (pagination)
	// Returns:
	//   - Filtered list of product fields including category name
	//   - total_count of all matching products for pagination UI
	// Business Logic:
	//   - Excludes soft-deleted products (deleted_at IS NULL)
	//   - Supports case-insensitive partial search on name and description
	//   - Filters by category ID only if provided
	//   - Filters by price range only if values provided (>= min_price and <= max_price)
	//   - Ordered by newest products first (created_at DESC)
	GetProductsByMerchant(ctx context.Context, arg GetProductsByMerchantParams) ([]*GetProductsByMerchantRow, error)
	// GetProductsTrashed: Retrieves paginated list of trashed (soft-deleted) products
	// Purpose: List deleted products for admin to manage recovery or audit
	// Parameters:
	//   $1: search_term - Optional text to filter trashed products (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All product fields plus total_count of matching trashed records
	// Business Logic:
	//   - Includes only soft-deleted products (deleted_at IS NOT NULL)
	//   - Supports partial, case-insensitive search on name, description, brand, slug, and barcode
	//   - Returns by newest first (created_at DESC)
	//   - Used for "Trash Bin" UI or soft-delete management
	GetProductsTrashed(ctx context.Context, arg GetProductsTrashedParams) ([]*GetProductsTrashedRow, error)
	// GetYearlyOrder: Retrieves yearly order summary over the past 5 years
	// Purpose: Enables long-term trend analysis of sales performance
	// Parameters:
	//   $1: Reference date (timestamp) - defines the 5-year analysis window
	// Returns:
	//   year: 4-digit year as string
	//   order_count: Total number of orders in the year
	//   total_revenue: Sum of total price from all orders
	//   total_items_sold: Total quantity of items sold in the year
	//   active_cashiers: Number of distinct cashier IDs involved in transactions
	//   unique_products_sold: Number of unique products sold
	// Business Logic:
	//   - Covers a rolling 5-year window up to the reference year
	//   - Filters out deleted records to ensure data consistency
	//   - Useful for high-level KPI tracking, forecasting, and strategic planning
	//   - Includes both volume and revenue metrics for comprehensive reporting
	//   - Results sorted by year in ascending order
	GetYearlyOrder(ctx context.Context, dollar_1 time.Time) ([]*GetYearlyOrderRow, error)
	// GetYearlyOrderByMerchant: Retrieves yearly order summary over the past 5 years by merchant_id
	// Purpose: Enables long-term trend analysis of sales performance
	// Parameters:
	//   $1: Reference date (timestamp) - defines the 5-year analysis window
	// Returns:
	//   year: 4-digit year as string
	//   order_count: Total number of orders in the year
	//   total_revenue: Sum of total price from all orders
	//   total_items_sold: Total quantity of items sold in the year
	//   active_cashiers: Number of distinct cashier IDs involved in transactions
	//   unique_products_sold: Number of unique products sold
	// Business Logic:
	//   - Covers a rolling 5-year window up to the reference year
	//   - Filters out deleted records to ensure data consistency
	//   - Useful for high-level KPI tracking, forecasting, and strategic planning
	//   - Includes both volume and revenue metrics for comprehensive reporting
	//   - Results sorted by year in ascending order
	GetYearlyOrderByMerchant(ctx context.Context, arg GetYearlyOrderByMerchantParams) ([]*GetYearlyOrderByMerchantRow, error)
	// GetYearlyTotalRevenue: Retrieves yearly total revenue for current and previous year
	// Purpose: Show year-over-year revenue trends
	// Parameters:
	//   $1: The current year (integer)
	// Returns:
	//   year: Year (as string)
	//   total_revenue: Total revenue (SUM of order totals) for the year (0 if no revenue)
	// Business Logic:
	//   - Automatically compares revenue between current and previous year
	//   - Includes zero-value years for complete data visualization
	//   - Filters only active/non-deleted orders and order items
	GetYearlyTotalRevenue(ctx context.Context, dollar_1 int32) ([]*GetYearlyTotalRevenueRow, error)
	// GetYearlyTotalRevenueById: Retrieves yearly total revenue for current and previous year by order_id
	// Purpose: Show year-over-year revenue trends
	// Parameters:
	//   $1: The current year (integer)
	//   $2: Order ID
	// Returns:
	//   year: Year (as string)
	//   total_revenue: Total revenue (SUM of order totals) for the year (0 if no revenue)
	// Business Logic:
	//   - Automatically compares revenue between current and previous year
	//   - Includes zero-value years for complete data visualization
	//   - Filters only active/non-deleted orders and order items
	GetYearlyTotalRevenueById(ctx context.Context, arg GetYearlyTotalRevenueByIdParams) ([]*GetYearlyTotalRevenueByIdRow, error)
	// GetYearlyTotalRevenueByMerchant: Retrieves yearly total revenue for current and previous year by merchant_id
	// Purpose: Show year-over-year revenue trends
	// Parameters:
	//   $1: The current year (integer)
	//   $2: Order ID
	// Returns:
	//   year: Year (as string)
	//   total_revenue: Total revenue (SUM of order totals) for the year (0 if no revenue)
	// Business Logic:
	//   - Automatically compares revenue between current and previous year
	//   - Includes zero-value years for complete data visualization
	//   - Filters only active/non-deleted orders and order items
	GetYearlyTotalRevenueByMerchant(ctx context.Context, arg GetYearlyTotalRevenueByMerchantParams) ([]*GetYearlyTotalRevenueByMerchantRow, error)
	// IncrementProductCountStock: Atomically increments product stock
	// Purpose: Restore inventory after a compensated order operation
	// Parameters:
	//   $1: product_id - Product to update
	//   $2: quantity - Amount to add to current stock
	// Returns: Updated product record
	// Business Logic:
	//   - Atomic increment (no lost update between read and write)
	//   - Refuses non-positive quantities
	IncrementProductCountStock(ctx context.Context, arg IncrementProductCountStockParams) (*Product, error)
	// RestoreAllProducts: Mass restoration of deleted products
	// Purpose: Reactivate all trashed products
	// Business Logic:
	//   - Bulk restore operation
	//   - Used during data recovery
	RestoreAllProducts(ctx context.Context) error
	// RestoreOrder: Recovers a soft-deleted order
	// Purpose: Reactivate a cancelled order
	// Parameters:
	//   $1: order_id - UUID of order to restore
	// Returns: The restored order record
	// Business Logic:
	//   - Nullifies deleted_at field
	//   - Only works on previously cancelled orders
	//   - Maintains all original order data
	RestoreOrder(ctx context.Context, orderID int32) (*Order, error)
	// RestoreProduct: Recovers a soft-deleted product
	// Purpose: Reactivate a removed product
	// Parameters:
	//   $1: product_id - Product to restore
	// Returns: The restored product
	// Business Logic:
	//   - Nullifies deleted_at
	//   - Returns product to active status
	RestoreProduct(ctx context.Context, productID int32) (*Product, error)
	// TrashProduct: Soft-deletes a product
	// Purpose: Remove product from active listings
	// Parameters:
	//   $1: product_id - Product to deactivate
	// Returns: The soft-deleted product
	// Business Logic:
	//   - Sets deleted_at timestamp
	//   - Preserves product data
	//   - Excludes from active queries
	TrashProduct(ctx context.Context, productID int32) (*Product, error)
	// TrashedOrder: Soft-deletes an order
	// Purpose: Cancel/void an order without permanent deletion
	// Parameters:
	//   $1: order_id - UUID of order to cancel
	// Returns: The soft-deleted order record
	// Business Logic:
	//   - Sets deleted_at to current timestamp
	//   - Preserves order data for reporting
	//   - Only processes active orders
	//   - Can be restored via RestoreOrder
	TrashedOrder(ctx context.Context, orderID int32) (*Order, error)
	// UpdateOrder: Modifies order information
	// Purpose: Update order details (primarily total price)
	// Parameters:
	//   $1: order_id - UUID of order to update
	//   $2: total_price - New total amount
	// Returns: Updated order record
	// Business Logic:
	//   - Auto-updates updated_at timestamp
	//   - Only modifies active (non-deleted) orders
	//   - Used when order items change
	//   - Should trigger recalculation of total_price
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (*Order, error)
	// UpdateOrderItem: Updates quantity and price of an existing order item
	// Purpose: Allows modification of product details in an order
	// Parameters:
	//   $1: order_item_id
	//   $2: new quantity
	//   $3: new price
	// Returns:
	//   The updated order item
	// Business Logic:
	//   - Applies changes only to active items
	//   - Automatically updates `updated_at` timestamp
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (*OrderItem, error)
	// UpdateProduct: Modifies product information
	// Purpose: Update product details
	// Parameters:
	//   $1: product_id - Target product ID
	//   $2: category_id - Updated category
	//   $3: name - Updated name
	//   $4: description - Updated description
	//   $5: price - Updated price
	//   $6: count_in_stock - Updated inventory count
	//   $7: brand - Updated brand
	//   $8: weight - Updated weight
	//   $9: image_product - Updated image
	//   $10: barcode - Updated barcode
	// Returns: Updated product record
	// Business Logic:
	//   - Auto-updates updated_at
	//   - Only modifies active products
	//   - Validates all fields
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (*Product, error)
	// UpdateProductCountStock: Updates inventory count
	// Purpose: Adjust product stock levels
	// Parameters:
	//   $1: product_id - Product to update
	//   $2: count_in_stock - New inventory count
	// Returns: Updated product record
	// Business Logic:
	//   - Dedicated stock adjustment function
	//   - Used when inventory changes
	//   - Validates non-negative quantity
	UpdateProductCountStock(ctx context.Context, arg UpdateProductCountStockParams) (*Product, error)
}

var _ Querier = (*Queries)(nil)
