// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Merchant struct {
	MerchantID   int32            `json:"merchant_id"`
	UserID       int32            `json:"user_id"`
	Name         string           `json:"name"`
	Description  *string          `json:"description"`
	Address      *string          `json:"address"`
	ContactEmail *string          `json:"contact_email"`
	ContactPhone *string          `json:"contact_phone"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

type MerchantDocument struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

type OutboxEvent struct {
	OutboxID      int64            `json:"outbox_id"`
	Topic         string           `json:"topic"`
	EventKey      string           `json:"event_key"`
	Payload       []byte           `json:"payload"`
	Status        string           `json:"status"`
	Attempts      int32            `json:"attempts"`
	NextAttemptAt time.Time        `json:"next_attempt_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	UserID           int32            `json:"user_id"`
	Firstname        string           `json:"firstname"`
	Lastname         string           `json:"lastname"`
	Email            string           `json:"email"`
	Password         string           `json:"password"`
	VerificationCode string           `json:"verification_code"`
	IsVerified       *bool            `json:"is_verified"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}
