// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ClaimPendingOutboxEvents: Atomically claims up to $1 pending events whose retry
	// window has elapsed. The claim extends next_attempt_at to $2 (the lease expiry)
	// so concurrent relay instances can never publish the same event twice; a crashed
	// worker's claim simply expires when the lease passes and the event is retried.
	ClaimPendingOutboxEvents(ctx context.Context, arg ClaimPendingOutboxEventsParams) ([]*OutboxEvent, error)
	// CreateMerchant: Creates a new merchant account
	// Purpose: Register a new merchant in the system
	// Parameters:
	//   $1: user_id - Associated user account ID
	//   $2: name - Business name
	//   $3: description - Business description
	//   $4: address - Physical address
	//   $5: contact_email - Business email
	//   $6: contact_phone - Business phone
	//   $7: status - Account status (active/inactive)
	// Returns: The created merchant record
	// Business Logic:
	//   - Sets created_at timestamp automatically
	//   - Requires all mandatory merchant fields
	//   - Status defaults to 'active' unless specified otherwise
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (*Merchant, error)
	CreateMerchantDocument(ctx context.Context, arg CreateMerchantDocumentParams) (*MerchantDocument, error)
	// CreateOutboxEvent: Inserts a pending outbox event for durable Kafka publish.
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (*OutboxEvent, error)
	DeleteAllPermanentMerchantDocuments(ctx context.Context) error
	// DeleteAllPermanentMerchants: Purges all trashed merchants
	// Purpose: Clean up all soft-deleted merchant records
	// Business Logic:
	//   - Irreversible bulk deletion operation
	//   - Only affects already soft-deleted records
	//   - Typically used during database maintenance
	//   - Should be restricted to admin users
	DeleteAllPermanentMerchants(ctx context.Context) error
	DeleteMerchantDocumentPermanently(ctx context.Context, documentID int32) error
	// DeleteMerchantPermanently: Hard-deletes a merchant
	// Purpose: Completely remove merchant from database
	// Parameters:
	//   $1: merchant_id - ID of merchant to delete
	// Business Logic:
	//   - Permanent deletion of already soft-deleted records
	//   - No return value (exec-only operation)
	//   - Irreversible action - use with caution
	//   - Should trigger cleanup of related records
	DeleteMerchantPermanently(ctx context.Context, merchantID int32) error
	// DeleteOldOutboxEvents: Purges delivered/dead events older than the cutoff.
	DeleteOldOutboxEvents(ctx context.Context, updatedAt pgtype.Timestamp) (int64, error)
	GetActiveMerchantDocuments(ctx context.Context, arg GetActiveMerchantDocumentsParams) ([]*GetActiveMerchantDocumentsRow, error)
	// GetMerchantByID: Retrieves active merchant by ID
	// Purpose: Fetch merchant details for display/editing
	// Parameters:
	//   $1: merchant_id - ID of merchant to retrieve
	// Returns: Full merchant record if found and active
	// Business Logic:
	//   - Excludes soft-deleted records
	//   - Returns single record or nothing
	//   - Used for merchant profile viewing and editing
	GetMerchantByID(ctx context.Context, merchantID int32) (*Merchant, error)
	GetMerchantDocument(ctx context.Context, documentID int32) (*MerchantDocument, error)
	GetMerchantDocuments(ctx context.Context, arg GetMerchantDocumentsParams) ([]*GetMerchantDocumentsRow, error)
	// GetMerchants: Retrieves paginated list of active merchants with search capability
	// Purpose: List all active merchants for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter merchants by name or email (NULL for no filter)
	//   $2: limit - Maximum number of records to return (pagination limit)
	//   $3: offset - Number of records to skip (pagination offset)
	// Returns:
	//   All merchant fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted merchants (deleted_at IS NULL)
	//   - Supports partial text matching on name and contact_email fields (case-insensitive ILIKE)
	//   - Returns newest merchants first (created_at DESC)
	//   - Provides total_count for client-side pagination calculations
	//   - Uses window function COUNT(*) OVER() for efficient total count
	GetMerchants(ctx context.Context, arg GetMerchantsParams) ([]*GetMerchantsRow, error)
	// GetMerchantsActive: Retrieves paginated list of active merchants (identical to GetMerchants)
	// Purpose: Maintains consistent API pattern with other active/trashed endpoints
	// Parameters:
	//   $1: search_term - Optional filter text for name/email
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns:
	//   Active merchant records with total_count
	// Business Logic:
	//   - Same functionality as GetMerchants
	//   - Exists for consistency in API design patterns
	// Note: Could be consolidated with GetMerchants if duplicate functionality is undesired
	GetMerchantsActive(ctx context.Context, arg GetMerchantsActiveParams) ([]*GetMerchantsActiveRow, error)
	// GetMerchantsTrashed: Retrieves paginated list of soft-deleted merchants
	// Purpose: View and manage deleted merchants for potential restoration
	// Parameters:
	//   $1: search_term - Optional text to filter trashed merchants
	//   $2: limit - Maximum records per page
	//   $3: offset - Records to skip
	// Returns:
	//   Trashed merchant records with total_count
	// Business Logic:
	//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
	//   - Maintains same search functionality as active merchant queries
	//   - Preserves chronological sorting (newest first)
	//   - Used in merchant recovery/audit interfaces
	//   - Includes total_count for pagination in trash management UI
	GetMerchantsTrashed(ctx context.Context, arg GetMerchantsTrashedParams) ([]*GetMerchantsTrashedRow, error)
	// GetPendingOutboxEvents: Returns pending events whose retry window has elapsed.
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]*OutboxEvent, error)
	GetTrashedMerchantDocuments(ctx context.Context, arg GetTrashedMerchantDocumentsParams) ([]*GetTrashedMerchantDocumentsRow, error)
	// MarkOutboxEventDead: Marks a pending event as dead after exhausting retries.
	MarkOutboxEventDead(ctx context.Context, outboxID int64) (*OutboxEvent, error)
	// MarkOutboxEventDelivered: Marks a pending event as delivered.
	MarkOutboxEventDelivered(ctx context.Context, outboxID int64) (*OutboxEvent, error)
	// MarkOutboxEventFailed: Increments the attempt counter and schedules the next
	// attempt at the provided timestamp (backoff computed by the caller).
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) (*OutboxEvent, error)
	RestoreAllMerchantDocuments(ctx context.Context) error
	// RestoreAllMerchants: Mass restoration of deleted merchants
	// Purpose: Recover all trashed merchants at once
	// Business Logic:
	//   - Reactivates all soft-deleted merchants
	//   - No parameters needed (bulk operation)
	//   - Typically used during system recovery
	//   - Maintains original merchant data
	RestoreAllMerchants(ctx context.Context) error
	// RestoreMerchant: Recovers a soft-deleted merchant
	// Purpose: Reactivate a previously deactivated merchant
	// Parameters:
	//   $1: merchant_id - ID of merchant to restore
	// Returns: The restored merchant record
	// Business Logic:
	//   - Nullifies the deleted_at field
	//   - Only works on previously deleted records
	//   - Preserves all original merchant data
	//   - Reactivates associated services
	RestoreMerchant(ctx context.Context, merchantID int32) (*Merchant, error)
	RestoreMerchantDocument(ctx context.Context, documentID int32) (*MerchantDocument, error)
	// TrashMerchant: Soft-deletes a merchant account
	// Purpose: Deactivate merchant without permanent deletion
	// Parameters:
	//   $1: merchant_id - ID of merchant to deactivate
	// Returns: The soft-deleted merchant record
	// Business Logic:
	//   - Sets deleted_at timestamp to current time
	//   - Only processes currently active records
	//   - Allows recovery via restore function
	//   - Maintains referential integrity
	TrashMerchant(ctx context.Context, merchantID int32) (*Merchant, error)
	TrashMerchantDocument(ctx context.Context, documentID int32) (*MerchantDocument, error)
	// UpdateMerchant: Modifies merchant information
	// Purpose: Update merchant profile details
	// Parameters:
	//   $1: merchant_id - Target merchant ID
	//   $2: name - Updated business name
	//   $3: description - Updated description
	//   $4: address - Updated physical address
	//   $5: contact_email - Updated email
	//   $6: contact_phone - Updated phone
	//   $7: status - Updated account status
	// Returns: Updated merchant record
	// Business Logic:
	//   - Automatically updates updated_at timestamp
	//   - Only affects active (non-deleted) records
	//   - Validates all required fields
	//   - Returns modified record for confirmation
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (*Merchant, error)
	UpdateMerchantDocument(ctx context.Context, arg UpdateMerchantDocumentParams) (*MerchantDocument, error)
	UpdateMerchantDocumentStatus(ctx context.Context, arg UpdateMerchantDocumentStatusParams) (*MerchantDocument, error)
	UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (*Merchant, error)
}

var _ Querier = (*Queries)(nil)
