// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: stats.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderStatsService_FindMonthlyTotalRevenue_FullMethodName   = "/pb.OrderStatsService/FindMonthlyTotalRevenue"
	OrderStatsService_FindYearlyTotalRevenue_FullMethodName    = "/pb.OrderStatsService/FindYearlyTotalRevenue"
	OrderStatsService_FindCashierMonthlyRevenue_FullMethodName = "/pb.OrderStatsService/FindCashierMonthlyRevenue"
)

// OrderStatsServiceClient is the client API for OrderStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderStatsServiceClient interface {
	FindMonthlyTotalRevenue(ctx context.Context, in *FindYearMonthStatsRequest, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyRevenue, error)
	FindYearlyTotalRevenue(ctx context.Context, in *FindYearStatsRequest, opts ...grpc.CallOption) (*ApiResponseOrderYearlyRevenue, error)
	FindCashierMonthlyRevenue(ctx context.Context, in *FindCashierStatsRequest, opts ...grpc.CallOption) (*ApiResponseCashierMonthlyRevenue, error)
}

type orderStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderStatsServiceClient(cc grpc.ClientConnInterface) OrderStatsServiceClient {
	return &orderStatsServiceClient{cc}
}

func (c *orderStatsServiceClient) FindMonthlyTotalRevenue(ctx context.Context, in *FindYearMonthStatsRequest, opts ...grpc.CallOption) (*ApiResponseOrderMonthlyRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderMonthlyRevenue)
	err := c.cc.Invoke(ctx, OrderStatsService_FindMonthlyTotalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindYearlyTotalRevenue(ctx context.Context, in *FindYearStatsRequest, opts ...grpc.CallOption) (*ApiResponseOrderYearlyRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderYearlyRevenue)
	err := c.cc.Invoke(ctx, OrderStatsService_FindYearlyTotalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderStatsServiceClient) FindCashierMonthlyRevenue(ctx context.Context, in *FindCashierStatsRequest, opts ...grpc.CallOption) (*ApiResponseCashierMonthlyRevenue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCashierMonthlyRevenue)
	err := c.cc.Invoke(ctx, OrderStatsService_FindCashierMonthlyRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderStatsServiceServer is the server API for OrderStatsService service.
// All implementations must embed UnimplementedOrderStatsServiceServer
// for forward compatibility.
type OrderStatsServiceServer interface {
	FindMonthlyTotalRevenue(context.Context, *FindYearMonthStatsRequest) (*ApiResponseOrderMonthlyRevenue, error)
	FindYearlyTotalRevenue(context.Context, *FindYearStatsRequest) (*ApiResponseOrderYearlyRevenue, error)
	FindCashierMonthlyRevenue(context.Context, *FindCashierStatsRequest) (*ApiResponseCashierMonthlyRevenue, error)
	mustEmbedUnimplementedOrderStatsServiceServer()
}

// UnimplementedOrderStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderStatsServiceServer struct{}

func (UnimplementedOrderStatsServiceServer) FindMonthlyTotalRevenue(context.Context, *FindYearMonthStatsRequest) (*ApiResponseOrderMonthlyRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalRevenue not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindYearlyTotalRevenue(context.Context, *FindYearStatsRequest) (*ApiResponseOrderYearlyRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalRevenue not implemented")
}
func (UnimplementedOrderStatsServiceServer) FindCashierMonthlyRevenue(context.Context, *FindCashierStatsRequest) (*ApiResponseCashierMonthlyRevenue, error) {
	return nil, status.Error(codes.Unimplemented, "method FindCashierMonthlyRevenue not implemented")
}
func (UnimplementedOrderStatsServiceServer) mustEmbedUnimplementedOrderStatsServiceServer() {}
func (UnimplementedOrderStatsServiceServer) testEmbeddedByValue()                           {}

// UnsafeOrderStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderStatsServiceServer will
// result in compilation errors.
type UnsafeOrderStatsServiceServer interface {
	mustEmbedUnimplementedOrderStatsServiceServer()
}

func RegisterOrderStatsServiceServer(s grpc.ServiceRegistrar, srv OrderStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderStatsService_ServiceDesc, srv)
}

func _OrderStatsService_FindMonthlyTotalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindMonthlyTotalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindMonthlyTotalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindMonthlyTotalRevenue(ctx, req.(*FindYearMonthStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindYearlyTotalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindYearlyTotalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindYearlyTotalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindYearlyTotalRevenue(ctx, req.(*FindYearStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderStatsService_FindCashierMonthlyRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCashierStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatsServiceServer).FindCashierMonthlyRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatsService_FindCashierMonthlyRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatsServiceServer).FindCashierMonthlyRevenue(ctx, req.(*FindCashierStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderStatsService_ServiceDesc is the grpc.ServiceDesc for OrderStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderStatsService",
	HandlerType: (*OrderStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalRevenue",
			Handler:    _OrderStatsService_FindMonthlyTotalRevenue_Handler,
		},
		{
			MethodName: "FindYearlyTotalRevenue",
			Handler:    _OrderStatsService_FindYearlyTotalRevenue_Handler,
		},
		{
			MethodName: "FindCashierMonthlyRevenue",
			Handler:    _OrderStatsService_FindCashierMonthlyRevenue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}

const (
	ProductStatsService_FindMonthlySold_FullMethodName = "/pb.ProductStatsService/FindMonthlySold"
)

// ProductStatsServiceClient is the client API for ProductStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductStatsServiceClient interface {
	FindMonthlySold(ctx context.Context, in *FindYearMonthStatsRequest, opts ...grpc.CallOption) (*ApiResponseProductMonthlySold, error)
}

type productStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductStatsServiceClient(cc grpc.ClientConnInterface) ProductStatsServiceClient {
	return &productStatsServiceClient{cc}
}

func (c *productStatsServiceClient) FindMonthlySold(ctx context.Context, in *FindYearMonthStatsRequest, opts ...grpc.CallOption) (*ApiResponseProductMonthlySold, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProductMonthlySold)
	err := c.cc.Invoke(ctx, ProductStatsService_FindMonthlySold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductStatsServiceServer is the server API for ProductStatsService service.
// All implementations must embed UnimplementedProductStatsServiceServer
// for forward compatibility.
type ProductStatsServiceServer interface {
	FindMonthlySold(context.Context, *FindYearMonthStatsRequest) (*ApiResponseProductMonthlySold, error)
	mustEmbedUnimplementedProductStatsServiceServer()
}

// UnimplementedProductStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductStatsServiceServer struct{}

func (UnimplementedProductStatsServiceServer) FindMonthlySold(context.Context, *FindYearMonthStatsRequest) (*ApiResponseProductMonthlySold, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlySold not implemented")
}
func (UnimplementedProductStatsServiceServer) mustEmbedUnimplementedProductStatsServiceServer() {}
func (UnimplementedProductStatsServiceServer) testEmbeddedByValue()                             {}

// UnsafeProductStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductStatsServiceServer will
// result in compilation errors.
type UnsafeProductStatsServiceServer interface {
	mustEmbedUnimplementedProductStatsServiceServer()
}

func RegisterProductStatsServiceServer(s grpc.ServiceRegistrar, srv ProductStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedProductStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductStatsService_ServiceDesc, srv)
}

func _ProductStatsService_FindMonthlySold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductStatsServiceServer).FindMonthlySold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductStatsService_FindMonthlySold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductStatsServiceServer).FindMonthlySold(ctx, req.(*FindYearMonthStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductStatsService_ServiceDesc is the grpc.ServiceDesc for ProductStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ProductStatsService",
	HandlerType: (*ProductStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlySold",
			Handler:    _ProductStatsService_FindMonthlySold_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}

const (
	CategoryStatsService_FindMonthlySold_FullMethodName = "/pb.CategoryStatsService/FindMonthlySold"
)

// CategoryStatsServiceClient is the client API for CategoryStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryStatsServiceClient interface {
	FindMonthlySold(ctx context.Context, in *FindYearMonthStatsRequest, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlySold, error)
}

type categoryStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryStatsServiceClient(cc grpc.ClientConnInterface) CategoryStatsServiceClient {
	return &categoryStatsServiceClient{cc}
}

func (c *categoryStatsServiceClient) FindMonthlySold(ctx context.Context, in *FindYearMonthStatsRequest, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlySold, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlySold)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthlySold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryStatsServiceServer is the server API for CategoryStatsService service.
// All implementations must embed UnimplementedCategoryStatsServiceServer
// for forward compatibility.
type CategoryStatsServiceServer interface {
	FindMonthlySold(context.Context, *FindYearMonthStatsRequest) (*ApiResponseCategoryMonthlySold, error)
	mustEmbedUnimplementedCategoryStatsServiceServer()
}

// UnimplementedCategoryStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryStatsServiceServer struct{}

func (UnimplementedCategoryStatsServiceServer) FindMonthlySold(context.Context, *FindYearMonthStatsRequest) (*ApiResponseCategoryMonthlySold, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlySold not implemented")
}
func (UnimplementedCategoryStatsServiceServer) mustEmbedUnimplementedCategoryStatsServiceServer() {}
func (UnimplementedCategoryStatsServiceServer) testEmbeddedByValue()                              {}

// UnsafeCategoryStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryStatsServiceServer will
// result in compilation errors.
type UnsafeCategoryStatsServiceServer interface {
	mustEmbedUnimplementedCategoryStatsServiceServer()
}

func RegisterCategoryStatsServiceServer(s grpc.ServiceRegistrar, srv CategoryStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedCategoryStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryStatsService_ServiceDesc, srv)
}

func _CategoryStatsService_FindMonthlySold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthlySold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthlySold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthlySold(ctx, req.(*FindYearMonthStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryStatsService_ServiceDesc is the grpc.ServiceDesc for CategoryStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CategoryStatsService",
	HandlerType: (*CategoryStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlySold",
			Handler:    _CategoryStatsService_FindMonthlySold_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}

const (
	TransactionStatsService_FindMonthlySuccess_FullMethodName = "/pb.TransactionStatsService/FindMonthlySuccess"
)

// TransactionStatsServiceClient is the client API for TransactionStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionStatsServiceClient interface {
	FindMonthlySuccess(ctx context.Context, in *FindYearMonthStatsRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthlySuccess, error)
}

type transactionStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionStatsServiceClient(cc grpc.ClientConnInterface) TransactionStatsServiceClient {
	return &transactionStatsServiceClient{cc}
}

func (c *transactionStatsServiceClient) FindMonthlySuccess(ctx context.Context, in *FindYearMonthStatsRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthlySuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthlySuccess)
	err := c.cc.Invoke(ctx, TransactionStatsService_FindMonthlySuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionStatsServiceServer is the server API for TransactionStatsService service.
// All implementations must embed UnimplementedTransactionStatsServiceServer
// for forward compatibility.
type TransactionStatsServiceServer interface {
	FindMonthlySuccess(context.Context, *FindYearMonthStatsRequest) (*ApiResponseTransactionMonthlySuccess, error)
	mustEmbedUnimplementedTransactionStatsServiceServer()
}

// UnimplementedTransactionStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionStatsServiceServer struct{}

func (UnimplementedTransactionStatsServiceServer) FindMonthlySuccess(context.Context, *FindYearMonthStatsRequest) (*ApiResponseTransactionMonthlySuccess, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlySuccess not implemented")
}
func (UnimplementedTransactionStatsServiceServer) mustEmbedUnimplementedTransactionStatsServiceServer() {
}
func (UnimplementedTransactionStatsServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionStatsServiceServer will
// result in compilation errors.
type UnsafeTransactionStatsServiceServer interface {
	mustEmbedUnimplementedTransactionStatsServiceServer()
}

func RegisterTransactionStatsServiceServer(s grpc.ServiceRegistrar, srv TransactionStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionStatsService_ServiceDesc, srv)
}

func _TransactionStatsService_FindMonthlySuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).FindMonthlySuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_FindMonthlySuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).FindMonthlySuccess(ctx, req.(*FindYearMonthStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionStatsService_ServiceDesc is the grpc.ServiceDesc for TransactionStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TransactionStatsService",
	HandlerType: (*TransactionStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlySuccess",
			Handler:    _TransactionStatsService_FindMonthlySuccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}

const (
	CashierStatsService_FindMonthlyOrders_FullMethodName = "/pb.CashierStatsService/FindMonthlyOrders"
)

// CashierStatsServiceClient is the client API for CashierStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CashierStatsServiceClient interface {
	FindMonthlyOrders(ctx context.Context, in *FindCashierStatsRequest, opts ...grpc.CallOption) (*ApiResponseCashierMonthlyOrders, error)
}

type cashierStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCashierStatsServiceClient(cc grpc.ClientConnInterface) CashierStatsServiceClient {
	return &cashierStatsServiceClient{cc}
}

func (c *cashierStatsServiceClient) FindMonthlyOrders(ctx context.Context, in *FindCashierStatsRequest, opts ...grpc.CallOption) (*ApiResponseCashierMonthlyOrders, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCashierMonthlyOrders)
	err := c.cc.Invoke(ctx, CashierStatsService_FindMonthlyOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CashierStatsServiceServer is the server API for CashierStatsService service.
// All implementations must embed UnimplementedCashierStatsServiceServer
// for forward compatibility.
type CashierStatsServiceServer interface {
	FindMonthlyOrders(context.Context, *FindCashierStatsRequest) (*ApiResponseCashierMonthlyOrders, error)
	mustEmbedUnimplementedCashierStatsServiceServer()
}

// UnimplementedCashierStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCashierStatsServiceServer struct{}

func (UnimplementedCashierStatsServiceServer) FindMonthlyOrders(context.Context, *FindCashierStatsRequest) (*ApiResponseCashierMonthlyOrders, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyOrders not implemented")
}
func (UnimplementedCashierStatsServiceServer) mustEmbedUnimplementedCashierStatsServiceServer() {}
func (UnimplementedCashierStatsServiceServer) testEmbeddedByValue()                             {}

// UnsafeCashierStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CashierStatsServiceServer will
// result in compilation errors.
type UnsafeCashierStatsServiceServer interface {
	mustEmbedUnimplementedCashierStatsServiceServer()
}

func RegisterCashierStatsServiceServer(s grpc.ServiceRegistrar, srv CashierStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedCashierStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CashierStatsService_ServiceDesc, srv)
}

func _CashierStatsService_FindMonthlyOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCashierStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierStatsServiceServer).FindMonthlyOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierStatsService_FindMonthlyOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierStatsServiceServer).FindMonthlyOrders(ctx, req.(*FindCashierStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CashierStatsService_ServiceDesc is the grpc.ServiceDesc for CashierStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CashierStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CashierStatsService",
	HandlerType: (*CashierStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyOrders",
			Handler:    _CashierStatsService_FindMonthlyOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}
