// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: stats.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindYearMonthStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearMonthStatsRequest) Reset() {
	*x = FindYearMonthStatsRequest{}
	mi := &file_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearMonthStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearMonthStatsRequest) ProtoMessage() {}

func (x *FindYearMonthStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearMonthStatsRequest.ProtoReflect.Descriptor instead.
func (*FindYearMonthStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *FindYearMonthStatsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearMonthStatsRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindYearStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearStatsRequest) Reset() {
	*x = FindYearStatsRequest{}
	mi := &file_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearStatsRequest) ProtoMessage() {}

func (x *FindYearStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearStatsRequest.ProtoReflect.Descriptor instead.
func (*FindYearStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

func (x *FindYearStatsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindCashierStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CashierId     int32                  `protobuf:"varint,1,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCashierStatsRequest) Reset() {
	*x = FindCashierStatsRequest{}
	mi := &file_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCashierStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCashierStatsRequest) ProtoMessage() {}

func (x *FindCashierStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCashierStatsRequest.ProtoReflect.Descriptor instead.
func (*FindCashierStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{2}
}

func (x *FindCashierStatsRequest) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

type OrderMonthlyRevenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	TotalRevenue  int64                  `protobuf:"varint,3,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	OrderCount    int32                  `protobuf:"varint,4,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderMonthlyRevenueResponse) Reset() {
	*x = OrderMonthlyRevenueResponse{}
	mi := &file_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderMonthlyRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMonthlyRevenueResponse) ProtoMessage() {}

func (x *OrderMonthlyRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMonthlyRevenueResponse.ProtoReflect.Descriptor instead.
func (*OrderMonthlyRevenueResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{3}
}

func (x *OrderMonthlyRevenueResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *OrderMonthlyRevenueResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *OrderMonthlyRevenueResponse) GetTotalRevenue() int64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *OrderMonthlyRevenueResponse) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

type OrderYearlyRevenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalRevenue  int64                  `protobuf:"varint,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	OrderCount    int32                  `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderYearlyRevenueResponse) Reset() {
	*x = OrderYearlyRevenueResponse{}
	mi := &file_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderYearlyRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderYearlyRevenueResponse) ProtoMessage() {}

func (x *OrderYearlyRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderYearlyRevenueResponse.ProtoReflect.Descriptor instead.
func (*OrderYearlyRevenueResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{4}
}

func (x *OrderYearlyRevenueResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *OrderYearlyRevenueResponse) GetTotalRevenue() int64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *OrderYearlyRevenueResponse) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

type CashierMonthlyRevenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	CashierId     int32                  `protobuf:"varint,3,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	TotalRevenue  int64                  `protobuf:"varint,4,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	OrderCount    int32                  `protobuf:"varint,5,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierMonthlyRevenueResponse) Reset() {
	*x = CashierMonthlyRevenueResponse{}
	mi := &file_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierMonthlyRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierMonthlyRevenueResponse) ProtoMessage() {}

func (x *CashierMonthlyRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierMonthlyRevenueResponse.ProtoReflect.Descriptor instead.
func (*CashierMonthlyRevenueResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{5}
}

func (x *CashierMonthlyRevenueResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *CashierMonthlyRevenueResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *CashierMonthlyRevenueResponse) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *CashierMonthlyRevenueResponse) GetTotalRevenue() int64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *CashierMonthlyRevenueResponse) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

type ApiResponseOrderMonthlyRevenue struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Status        string                         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderMonthlyRevenueResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderMonthlyRevenue) Reset() {
	*x = ApiResponseOrderMonthlyRevenue{}
	mi := &file_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderMonthlyRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderMonthlyRevenue) ProtoMessage() {}

func (x *ApiResponseOrderMonthlyRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderMonthlyRevenue.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderMonthlyRevenue) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseOrderMonthlyRevenue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderMonthlyRevenue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseOrderMonthlyRevenue) GetData() []*OrderMonthlyRevenueResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseOrderYearlyRevenue struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Status        string                        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderYearlyRevenueResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderYearlyRevenue) Reset() {
	*x = ApiResponseOrderYearlyRevenue{}
	mi := &file_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderYearlyRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderYearlyRevenue) ProtoMessage() {}

func (x *ApiResponseOrderYearlyRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderYearlyRevenue.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderYearlyRevenue) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponseOrderYearlyRevenue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderYearlyRevenue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseOrderYearlyRevenue) GetData() []*OrderYearlyRevenueResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCashierMonthlyRevenue struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierMonthlyRevenueResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierMonthlyRevenue) Reset() {
	*x = ApiResponseCashierMonthlyRevenue{}
	mi := &file_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierMonthlyRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierMonthlyRevenue) ProtoMessage() {}

func (x *ApiResponseCashierMonthlyRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierMonthlyRevenue.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierMonthlyRevenue) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponseCashierMonthlyRevenue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierMonthlyRevenue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierMonthlyRevenue) GetData() []*CashierMonthlyRevenueResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProductMonthlySoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Subtotal      int64                  `protobuf:"varint,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductMonthlySoldResponse) Reset() {
	*x = ProductMonthlySoldResponse{}
	mi := &file_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductMonthlySoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductMonthlySoldResponse) ProtoMessage() {}

func (x *ProductMonthlySoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductMonthlySoldResponse.ProtoReflect.Descriptor instead.
func (*ProductMonthlySoldResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{9}
}

func (x *ProductMonthlySoldResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *ProductMonthlySoldResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductMonthlySoldResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductMonthlySoldResponse) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

type CategoryMonthlySoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Subtotal      int64                  `protobuf:"varint,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryMonthlySoldResponse) Reset() {
	*x = CategoryMonthlySoldResponse{}
	mi := &file_stats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryMonthlySoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryMonthlySoldResponse) ProtoMessage() {}

func (x *CategoryMonthlySoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryMonthlySoldResponse.ProtoReflect.Descriptor instead.
func (*CategoryMonthlySoldResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{10}
}

func (x *CategoryMonthlySoldResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *CategoryMonthlySoldResponse) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryMonthlySoldResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CategoryMonthlySoldResponse) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

type ApiResponseProductMonthlySold struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Status        string                        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ProductMonthlySoldResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseProductMonthlySold) Reset() {
	*x = ApiResponseProductMonthlySold{}
	mi := &file_stats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseProductMonthlySold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseProductMonthlySold) ProtoMessage() {}

func (x *ApiResponseProductMonthlySold) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseProductMonthlySold.ProtoReflect.Descriptor instead.
func (*ApiResponseProductMonthlySold) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponseProductMonthlySold) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseProductMonthlySold) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseProductMonthlySold) GetData() []*ProductMonthlySoldResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCategoryMonthlySold struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Status        string                         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CategoryMonthlySoldResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCategoryMonthlySold) Reset() {
	*x = ApiResponseCategoryMonthlySold{}
	mi := &file_stats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCategoryMonthlySold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCategoryMonthlySold) ProtoMessage() {}

func (x *ApiResponseCategoryMonthlySold) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCategoryMonthlySold.ProtoReflect.Descriptor instead.
func (*ApiResponseCategoryMonthlySold) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{12}
}

func (x *ApiResponseCategoryMonthlySold) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCategoryMonthlySold) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCategoryMonthlySold) GetData() []*CategoryMonthlySoldResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type TransactionMonthlySuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionMonthlySuccessResponse) Reset() {
	*x = TransactionMonthlySuccessResponse{}
	mi := &file_stats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMonthlySuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMonthlySuccessResponse) ProtoMessage() {}

func (x *TransactionMonthlySuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMonthlySuccessResponse.ProtoReflect.Descriptor instead.
func (*TransactionMonthlySuccessResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{13}
}

func (x *TransactionMonthlySuccessResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TransactionMonthlySuccessResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *TransactionMonthlySuccessResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ApiResponseTransactionMonthlySuccess struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Status        string                               `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionMonthlySuccessResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionMonthlySuccess) Reset() {
	*x = ApiResponseTransactionMonthlySuccess{}
	mi := &file_stats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionMonthlySuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionMonthlySuccess) ProtoMessage() {}

func (x *ApiResponseTransactionMonthlySuccess) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionMonthlySuccess.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionMonthlySuccess) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{14}
}

func (x *ApiResponseTransactionMonthlySuccess) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionMonthlySuccess) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionMonthlySuccess) GetData() []*TransactionMonthlySuccessResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type CashierMonthlyOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	CashierId     int32                  `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	OrderCount    int64                  `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierMonthlyOrdersResponse) Reset() {
	*x = CashierMonthlyOrdersResponse{}
	mi := &file_stats_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierMonthlyOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierMonthlyOrdersResponse) ProtoMessage() {}

func (x *CashierMonthlyOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierMonthlyOrdersResponse.ProtoReflect.Descriptor instead.
func (*CashierMonthlyOrdersResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{15}
}

func (x *CashierMonthlyOrdersResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *CashierMonthlyOrdersResponse) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *CashierMonthlyOrdersResponse) GetOrderCount() int64 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *CashierMonthlyOrdersResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ApiResponseCashierMonthlyOrders struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Status        string                          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierMonthlyOrdersResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierMonthlyOrders) Reset() {
	*x = ApiResponseCashierMonthlyOrders{}
	mi := &file_stats_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierMonthlyOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierMonthlyOrders) ProtoMessage() {}

func (x *ApiResponseCashierMonthlyOrders) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierMonthlyOrders.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierMonthlyOrders) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{16}
}

func (x *ApiResponseCashierMonthlyOrders) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierMonthlyOrders) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierMonthlyOrders) GetData() []*CashierMonthlyOrdersResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_stats_proto protoreflect.FileDescriptor

const file_stats_proto_rawDesc = "" +
	"\n" +
	"\vstats.proto\x12\x02pb\"E\n" +
	"\x19FindYearMonthStatsRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"*\n" +
	"\x14FindYearStatsRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"8\n" +
	"\x17FindCashierStatsRequest\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x01 \x01(\x05R\tcashierId\"\x8d\x01\n" +
	"\x1bOrderMonthlyRevenueResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12#\n" +
	"\rtotal_revenue\x18\x03 \x01(\x03R\ftotalRevenue\x12\x1f\n" +
	"\vorder_count\x18\x04 \x01(\x05R\n" +
	"orderCount\"v\n" +
	"\x1aOrderYearlyRevenueResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12#\n" +
	"\rtotal_revenue\x18\x02 \x01(\x03R\ftotalRevenue\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\x05R\n" +
	"orderCount\"\xae\x01\n" +
	"\x1dCashierMonthlyRevenueResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x03 \x01(\x05R\tcashierId\x12#\n" +
	"\rtotal_revenue\x18\x04 \x01(\x03R\ftotalRevenue\x12\x1f\n" +
	"\vorder_count\x18\x05 \x01(\x05R\n" +
	"orderCount\"\x87\x01\n" +
	"\x1eApiResponseOrderMonthlyRevenue\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x03(\v2\x1f.pb.OrderMonthlyRevenueResponseR\x04data\"\x85\x01\n" +
	"\x1dApiResponseOrderYearlyRevenue\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04data\x18\x03 \x03(\v2\x1e.pb.OrderYearlyRevenueResponseR\x04data\"\x8b\x01\n" +
	" ApiResponseCashierMonthlyRevenue\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x03 \x03(\v2!.pb.CashierMonthlyRevenueResponseR\x04data\"\x89\x01\n" +
	"\x1aProductMonthlySoldResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x1a\n" +
	"\bsubtotal\x18\x04 \x01(\x03R\bsubtotal\"\x8c\x01\n" +
	"\x1bCategoryMonthlySoldResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x1a\n" +
	"\bsubtotal\x18\x04 \x01(\x03R\bsubtotal\"\x85\x01\n" +
	"\x1dApiResponseProductMonthlySold\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04data\x18\x03 \x03(\v2\x1e.pb.ProductMonthlySoldResponseR\x04data\"\x87\x01\n" +
	"\x1eApiResponseCategoryMonthlySold\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x03(\v2\x1f.pb.CategoryMonthlySoldResponseR\x04data\"}\n" +
	"!TransactionMonthlySuccessResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\"\x93\x01\n" +
	"$ApiResponseTransactionMonthlySuccess\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x03(\v2%.pb.TransactionMonthlySuccessResponseR\x04data\"\x97\x01\n" +
	"\x1cCashierMonthlyOrdersResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x05R\tcashierId\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\x03R\n" +
	"orderCount\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x03R\vtotalAmount\"\x89\x01\n" +
	"\x1fApiResponseCashierMonthlyOrders\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x04data\x18\x03 \x03(\v2 .pb.CashierMonthlyOrdersResponseR\x04data2\xa8\x02\n" +
	"\x11OrderStatsService\x12\\\n" +
	"\x17FindMonthlyTotalRevenue\x12\x1d.pb.FindYearMonthStatsRequest\x1a\".pb.ApiResponseOrderMonthlyRevenue\x12U\n" +
	"\x16FindYearlyTotalRevenue\x12\x18.pb.FindYearStatsRequest\x1a!.pb.ApiResponseOrderYearlyRevenue\x12^\n" +
	"\x19FindCashierMonthlyRevenue\x12\x1b.pb.FindCashierStatsRequest\x1a$.pb.ApiResponseCashierMonthlyRevenue2j\n" +
	"\x13ProductStatsService\x12S\n" +
	"\x0fFindMonthlySold\x12\x1d.pb.FindYearMonthStatsRequest\x1a!.pb.ApiResponseProductMonthlySold2l\n" +
	"\x14CategoryStatsService\x12T\n" +
	"\x0fFindMonthlySold\x12\x1d.pb.FindYearMonthStatsRequest\x1a\".pb.ApiResponseCategoryMonthlySold2x\n" +
	"\x17TransactionStatsService\x12]\n" +
	"\x12FindMonthlySuccess\x12\x1d.pb.FindYearMonthStatsRequest\x1a(.pb.ApiResponseTransactionMonthlySuccess2l\n" +
	"\x13CashierStatsService\x12U\n" +
	"\x11FindMonthlyOrders\x12\x1b.pb.FindCashierStatsRequest\x1a#.pb.ApiResponseCashierMonthlyOrdersB<Z:github.com/MamangRust/microservice-point-of-sale-shared/pbb\x06proto3"

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData []byte
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)))
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_stats_proto_goTypes = []any{
	(*FindYearMonthStatsRequest)(nil),            // 0: pb.FindYearMonthStatsRequest
	(*FindYearStatsRequest)(nil),                 // 1: pb.FindYearStatsRequest
	(*FindCashierStatsRequest)(nil),              // 2: pb.FindCashierStatsRequest
	(*OrderMonthlyRevenueResponse)(nil),          // 3: pb.OrderMonthlyRevenueResponse
	(*OrderYearlyRevenueResponse)(nil),           // 4: pb.OrderYearlyRevenueResponse
	(*CashierMonthlyRevenueResponse)(nil),        // 5: pb.CashierMonthlyRevenueResponse
	(*ApiResponseOrderMonthlyRevenue)(nil),       // 6: pb.ApiResponseOrderMonthlyRevenue
	(*ApiResponseOrderYearlyRevenue)(nil),        // 7: pb.ApiResponseOrderYearlyRevenue
	(*ApiResponseCashierMonthlyRevenue)(nil),     // 8: pb.ApiResponseCashierMonthlyRevenue
	(*ProductMonthlySoldResponse)(nil),           // 9: pb.ProductMonthlySoldResponse
	(*CategoryMonthlySoldResponse)(nil),          // 10: pb.CategoryMonthlySoldResponse
	(*ApiResponseProductMonthlySold)(nil),        // 11: pb.ApiResponseProductMonthlySold
	(*ApiResponseCategoryMonthlySold)(nil),       // 12: pb.ApiResponseCategoryMonthlySold
	(*TransactionMonthlySuccessResponse)(nil),    // 13: pb.TransactionMonthlySuccessResponse
	(*ApiResponseTransactionMonthlySuccess)(nil), // 14: pb.ApiResponseTransactionMonthlySuccess
	(*CashierMonthlyOrdersResponse)(nil),         // 15: pb.CashierMonthlyOrdersResponse
	(*ApiResponseCashierMonthlyOrders)(nil),      // 16: pb.ApiResponseCashierMonthlyOrders
}
var file_stats_proto_depIdxs = []int32{
	3,  // 0: pb.ApiResponseOrderMonthlyRevenue.data:type_name -> pb.OrderMonthlyRevenueResponse
	4,  // 1: pb.ApiResponseOrderYearlyRevenue.data:type_name -> pb.OrderYearlyRevenueResponse
	5,  // 2: pb.ApiResponseCashierMonthlyRevenue.data:type_name -> pb.CashierMonthlyRevenueResponse
	9,  // 3: pb.ApiResponseProductMonthlySold.data:type_name -> pb.ProductMonthlySoldResponse
	10, // 4: pb.ApiResponseCategoryMonthlySold.data:type_name -> pb.CategoryMonthlySoldResponse
	13, // 5: pb.ApiResponseTransactionMonthlySuccess.data:type_name -> pb.TransactionMonthlySuccessResponse
	15, // 6: pb.ApiResponseCashierMonthlyOrders.data:type_name -> pb.CashierMonthlyOrdersResponse
	0,  // 7: pb.OrderStatsService.FindMonthlyTotalRevenue:input_type -> pb.FindYearMonthStatsRequest
	1,  // 8: pb.OrderStatsService.FindYearlyTotalRevenue:input_type -> pb.FindYearStatsRequest
	2,  // 9: pb.OrderStatsService.FindCashierMonthlyRevenue:input_type -> pb.FindCashierStatsRequest
	0,  // 10: pb.ProductStatsService.FindMonthlySold:input_type -> pb.FindYearMonthStatsRequest
	0,  // 11: pb.CategoryStatsService.FindMonthlySold:input_type -> pb.FindYearMonthStatsRequest
	0,  // 12: pb.TransactionStatsService.FindMonthlySuccess:input_type -> pb.FindYearMonthStatsRequest
	2,  // 13: pb.CashierStatsService.FindMonthlyOrders:input_type -> pb.FindCashierStatsRequest
	6,  // 14: pb.OrderStatsService.FindMonthlyTotalRevenue:output_type -> pb.ApiResponseOrderMonthlyRevenue
	7,  // 15: pb.OrderStatsService.FindYearlyTotalRevenue:output_type -> pb.ApiResponseOrderYearlyRevenue
	8,  // 16: pb.OrderStatsService.FindCashierMonthlyRevenue:output_type -> pb.ApiResponseCashierMonthlyRevenue
	11, // 17: pb.ProductStatsService.FindMonthlySold:output_type -> pb.ApiResponseProductMonthlySold
	12, // 18: pb.CategoryStatsService.FindMonthlySold:output_type -> pb.ApiResponseCategoryMonthlySold
	14, // 19: pb.TransactionStatsService.FindMonthlySuccess:output_type -> pb.ApiResponseTransactionMonthlySuccess
	16, // 20: pb.CashierStatsService.FindMonthlyOrders:output_type -> pb.ApiResponseCashierMonthlyOrders
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
