// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// CreateRole: Inserts a new role into the system
	// Purpose: Add new role definitions (e.g., Admin, Cashier, etc.)
	// Parameters:
	//   $1: Role name
	// Returns:
	//   Newly created role's full data (including timestamps)
	CreateRole(ctx context.Context, roleName string) (*Role, error)
	// CreateUser: Creates a new user account
	// Purpose: Register a new user in the system
	// Parameters:
	//   $1: firstname - User's first name
	//   $2: lastname - User's last name
	//   $3: email - User's email address (must be unique)
	//   $4: password - Hashed password string
	// Returns: The complete created user record
	// Business Logic:
	//   - Sets created_at and updated_at timestamps automatically
	//   - Requires all mandatory user fields
	//   - Email must be unique across the system
	//   - Password should be pre-hashed before insertion
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	// DeleteAllPermanentRoles: Permanently deletes all soft-deleted roles
	// Purpose: Bulk cleanup of trashed roles
	// Parameters: None
	DeleteAllPermanentRoles(ctx context.Context) error
	// DeleteAllPermanentUsers: Purges all trashed users
	// Purpose: Clean up all soft-deleted user records
	// Business Logic:
	//   - Irreversible bulk deletion operation
	//   - Only affects already soft-deleted users
	//   - Typically used during database maintenance
	//   - Should be restricted to admin users
	DeleteAllPermanentUsers(ctx context.Context) error
	// DeletePermanentRole: Permanently deletes a trashed role
	// Purpose: Remove role from DB after soft delete
	// Parameters:
	//   $1: Role ID
	DeletePermanentRole(ctx context.Context, roleID int32) error
	// DeleteUserPermanently: Hard-deletes a user account
	// Purpose: Completely remove user from database
	// Parameters:
	//   $1: user_id - ID of user to delete
	// Business Logic:
	//   - Permanent deletion of already soft-deleted users
	//   - No return value (exec-only operation)
	//   - Irreversible action - use with caution
	//   - Should trigger cleanup of related records
	DeleteUserPermanently(ctx context.Context, userID int32) error
	// GetActiveRoles: Retrieves only active (non-deleted) roles with optional search and pagination
	// Purpose: Display roles that are currently usable in the system
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetActiveRoles(ctx context.Context, arg GetActiveRolesParams) ([]*GetActiveRolesRow, error)
	// GetRole: Retrieves role details by role_id
	// Purpose: Fetch a single role record (regardless of deleted status)
	// Parameters:
	//   $1: Role ID
	// Returns:
	//   role_id, role_name, and timestamps
	GetRole(ctx context.Context, roleID int32) (*Role, error)
	// GetRoleByName: Retrieves role by exact role name
	// Purpose: Check role existence or fetch role info based on name
	// Parameters:
	//   $1: Role name (exact match)
	// Returns:
	//   role_id, role_name, and timestamps
	GetRoleByName(ctx context.Context, roleName string) (*Role, error)
	// GetRoles: Retrieves all roles (active & trashed) with optional name search and pagination
	// Purpose: General listing of roles regardless of status
	// Parameters:
	//   $1: Search query (role name, nullable)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting index for pagination)
	// Returns:
	//   role_id, role_name, timestamps, and total_count (for pagination support)
	// Business Logic:
	//   - Supports fuzzy search on role_name
	//   - Includes both active and trashed roles
	//   - Useful for admin panels with filters and pagination
	GetRoles(ctx context.Context, arg GetRolesParams) ([]*GetRolesRow, error)
	// GetTrashedRoles: Retrieves only soft-deleted roles with optional search and pagination
	// Purpose: For trash/recycle bin management
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, role_name, timestamps, and total_count
	GetTrashedRoles(ctx context.Context, arg GetTrashedRolesParams) ([]*GetTrashedRolesRow, error)
	// GetUserByEmail: Retrieves active user by email
	// Purpose: Lookup user by email address (for authentication)
	// Parameters:
	//   $1: email - Exact email address to search for
	// Returns: User record if found and active
	// Business Logic:
	//   - Case-sensitive exact match on email
	//   - Excludes deleted users
	//   - Used during login/authentication flows
	//   - Helps prevent duplicate accounts
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	// Purpose: Retrieve a verified user by their email.
	// Parameters:
	//   $1: email - The email of the user to fetch.
	// Returns:
	//   - User record where email matches, user is verified, and not deleted.
	// Business Logic:
	//   - Must match email exactly.
	//   - `is_verified` must be true.
	//   - `deleted_at` must be NULL (not soft-deleted).
	GetUserByEmailAndVerified(ctx context.Context, email string) (*User, error)
	// GetUserByID: Retrieves active user by ID
	// Purpose: Fetch specific user details
	// Parameters:
	//   $1: user_id - ID of user to retrieve
	// Returns: Full user record if found and active
	// Business Logic:
	//   - Excludes deleted users
	//   - Used for user profile viewing/editing
	//   - Primary lookup for user management
	GetUserByID(ctx context.Context, userID int32) (*User, error)
	// Purpose: Fetch a user based on their verification code.
	// Parameters:
	//   $1: verification_code - The verification code of the user to fetch.
	// Returns:
	//   - User record matching the provided verification code.
	// Business Logic:
	//   - Filters the users table to find a user based on their verification code.
	GetUserByVerificationCode(ctx context.Context, verificationCode string) (*User, error)
	// GetUserRoles: Retrieves all roles assigned to a specific user
	// Purpose: Identify the access level(s) of a user
	// Parameters:
	//   $1: User ID
	// Returns:
	//   List of roles (id, name, timestamps)
	GetUserRoles(ctx context.Context, userID int32) ([]*Role, error)
	// GetUserTrashed: Retrieves paginated list of soft-deleted users
	// Purpose: View and manage deleted users for potential restoration
	// Parameters:
	//   $1: search_term - Optional text to filter trashed users
	//   $2: limit - Maximum records per page
	//   $3: offset - Records to skip
	// Returns:
	//   Trashed user records with total_count
	// Business Logic:
	//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
	//   - Maintains same search functionality as active user queries
	//   - Preserves chronological sorting (newest first)
	//   - Used in user recovery/audit interfaces
	//   - Includes total_count for pagination in trash management UI
	GetUserTrashed(ctx context.Context, arg GetUserTrashedParams) ([]*GetUserTrashedRow, error)
	// GetUsers: Retrieves paginated list of active users with search capability
	// Purpose: List all active users for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter users by name or email (NULL for no filter)
	//   $2: limit - Maximum number of records to return (pagination limit)
	//   $3: offset - Number of records to skip (pagination offset)
	// Returns:
	//   All user fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted users (deleted_at IS NULL)
	//   - Supports partial text matching on firstname, lastname, and email fields (case-insensitive)
	//   - Returns newest users first (created_at DESC)
	//   - Provides total_count for client-side pagination
	//   - Uses window function COUNT(*) OVER() for efficient total count
	GetUsers(ctx context.Context, arg GetUsersParams) ([]*GetUsersRow, error)
	// GetUsersActive: Retrieves paginated list of active users (identical to GetUsers)
	// Purpose: Maintains consistent API pattern with other active/trashed endpoints
	// Parameters:
	//   $1: search_term - Optional filter text for name/email
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns:
	//   Active user records with total_count
	// Business Logic:
	//   - Same functionality as GetUsers
	//   - Exists for consistency in API design patterns
	// Note: Could be consolidated with GetUsers if duplicate functionality is undesired
	GetUsersActive(ctx context.Context, arg GetUsersActiveParams) ([]*GetUsersActiveRow, error)
	// RestoreAllRoles: Restores all soft-deleted roles in bulk
	// Purpose: Bulk recovery of all trashed roles
	// Parameters: None
	RestoreAllRoles(ctx context.Context) error
	// RestoreAllUsers: Mass restoration of deleted users
	// Purpose: Recover all trashed users at once
	// Business Logic:
	//   - Reactivates all soft-deleted users
	//   - No parameters needed (bulk operation)
	//   - Typically used during system recovery
	//   - Maintains all original user data
	RestoreAllUsers(ctx context.Context) error
	// RestoreRole: Restores a previously trashed role
	// Purpose: Undelete a soft-deleted role
	// Parameters:
	//   $1: Role ID
	RestoreRole(ctx context.Context, roleID int32) (*Role, error)
	// RestoreUser: Recovers a soft-deleted user
	// Purpose: Reactivate a previously deactivated user
	// Parameters:
	//   $1: user_id - ID of user to restore
	// Returns: The restored user record
	// Business Logic:
	//   - Nullifies the deleted_at field
	//   - Only works on previously deleted users
	//   - Restores full account access
	//   - Maintains all original user data
	RestoreUser(ctx context.Context, userID int32) (*User, error)
	// TrashRole: Soft-deletes a role (moves to trash)
	// Purpose: Mark role as deleted without removing it permanently
	// Parameters:
	//   $1: Role ID
	TrashRole(ctx context.Context, roleID int32) (*Role, error)
	// TrashUser: Soft-deletes a user account
	// Purpose: Deactivate user without permanent deletion
	// Parameters:
	//   $1: user_id - ID of user to deactivate
	// Returns: The soft-deleted user record
	// Business Logic:
	//   - Sets deleted_at timestamp to current time
	//   - Only processes currently active users
	//   - Preserves all user data for potential restoration
	//   - Prevents login while deleted
	TrashUser(ctx context.Context, userID int32) (*User, error)
	// UpdateRole: Updates role name by ID
	// Purpose: Modify role information (e.g., name correction)
	// Parameters:
	//   $1: Role ID
	//   $2: New role name
	// Returns:
	//   Updated role's data
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
	// UpdateUser: Modifies user account information
	// Purpose: Update user profile details
	// Parameters:
	//   $1: user_id - ID of user to update
	//   $2: firstname - Updated first name
	//   $3: lastname - Updated last name
	//   $4: email - Updated email address
	//   $5: password - New hashed password (optional)
	// Returns: Updated user record
	// Business Logic:
	//   - Auto-updates updated_at timestamp
	//   - Only modifies active (non-deleted) users
	//   - Validates email uniqueness
	//   - Password field optional (can maintain existing)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
	UpdateUserIsVerified(ctx context.Context, arg UpdateUserIsVerifiedParams) (*User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
