// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cashier struct {
	CashierID  int32            `json:"cashier_id"`
	MerchantID int32            `json:"merchant_id"`
	UserID     int32            `json:"user_id"`
	Name       string           `json:"name"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type Merchant struct {
	MerchantID   int32            `json:"merchant_id"`
	UserID       int32            `json:"user_id"`
	Name         string           `json:"name"`
	Description  *string          `json:"description"`
	Address      *string          `json:"address"`
	ContactEmail *string          `json:"contact_email"`
	ContactPhone *string          `json:"contact_phone"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

type Order struct {
	OrderID    int32            `json:"order_id"`
	MerchantID int32            `json:"merchant_id"`
	CashierID  int32            `json:"cashier_id"`
	TotalPrice int64            `json:"total_price"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type OrderItem struct {
	OrderItemID int32            `json:"order_item_id"`
	OrderID     int32            `json:"order_id"`
	ProductID   int32            `json:"product_id"`
	Quantity    int32            `json:"quantity"`
	Price       int32            `json:"price"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type Transaction struct {
	TransactionID int32            `json:"transaction_id"`
	OrderID       int32            `json:"order_id"`
	MerchantID    int32            `json:"merchant_id"`
	PaymentMethod string           `json:"payment_method"`
	Amount        int32            `json:"amount"`
	ChangeAmount  *int32           `json:"change_amount"`
	PaymentStatus string           `json:"payment_status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
}
