// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	// CreateTransaction: Creates a new transaction record
	// Purpose: Record a new payment transaction
	// Parameters:
	//   $1: merchant_id - Merchant reference
	//   $2: payment_method - Payment method used
	//   $3: amount - Transaction amount
	//   $4: change_amount - Change amount (if applicable)
	//   $5: payment_status - Payment status ('success', 'failed', 'pending')
	//   $6: order_id - Associated order reference
	// Returns: Newly created transaction record
	// Business Logic:
	//   - Sets created_at and updated_at timestamps
	//   - Initializes deleted_at as NULL
	//   - Validates all payment fields
	//   - Used for recording new payments
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (*Transaction, error)
	// DeleteAllPermanentTransactions: Purges all cancelled transactions
	// Purpose: Clean up all soft-deleted transaction records
	// Business Logic:
	//   - Irreversible bulk deletion operation
	//   - Only affects already cancelled transactions
	//   - Typically used during database maintenance
	//   - Should be restricted to admin users
	DeleteAllPermanentTransactions(ctx context.Context) error
	// DeleteTransactionPermanently: Hard-deletes a transaction
	// Purpose: Completely remove transaction from database
	// Parameters:
	//   $1: transaction_id - ID of transaction to delete
	// Business Logic:
	//   - Permanent deletion of already cancelled transactions
	//   - No return value (exec-only operation)
	//   - Irreversible action - use with caution
	//   - Should be restricted to admin users
	DeleteTransactionPermanently(ctx context.Context, transactionID int32) error
	// GetMonthlyAmountTransactionFailed: Retrieves monthly failed transaction metrics
	// Purpose: Generate monthly reports of failed transactions for analysis
	// Parameters:
	//   $1: Start date of first comparison period (timestamp)
	//   $2: End date of first comparison period (timestamp)
	//   $3: Start date of second comparison period (timestamp)
	//   $4: End date of second comparison period (timestamp)
	// Returns:
	//   year: Year as text
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   total_failed: Count of failed transactions
	//   total_amount: Sum of failed transaction amounts
	// Business Logic:
	//   - Only includes failed (payment_status = 'failed') transactions
	//   - Excludes deleted transactions
	//   - Compares two customizable time periods
	//   - Includes gap-filling for months with no failed transactions
	//   - Returns 0 values for months with no failed transactions
	//   - Orders by most recent year/month first
	GetMonthlyAmountTransactionFailed(ctx context.Context, arg GetMonthlyAmountTransactionFailedParams) ([]*GetMonthlyAmountTransactionFailedRow, error)
	// GetMonthlyAmountTransactionFailedByMerchant: Retrieves monthly failed transaction metrics
	// Purpose: Generate monthly reports of failed transactions for analysis by merchant_id
	// Parameters:
	//   $1: Start date of first comparison period (timestamp)
	//   $2: End date of first comparison period (timestamp)
	//   $3: Start date of second comparison period (timestamp)
	//   $4: End date of second comparison period (timestamp)
	//   $5: Merchant ID
	// Returns:
	//   year: Year as text
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   total_failed: Count of failed transactions
	//   total_amount: Sum of failed transaction amounts
	// Business Logic:
	//   - Only includes failed (payment_status = 'failed') transactions
	//   - Excludes deleted transactions
	//   - Compares two customizable time periods
	//   - Includes gap-filling for months with no failed transactions
	//   - Returns 0 values for months with no failed transactions
	//   - Orders by most recent year/month first
	GetMonthlyAmountTransactionFailedByMerchant(ctx context.Context, arg GetMonthlyAmountTransactionFailedByMerchantParams) ([]*GetMonthlyAmountTransactionFailedByMerchantRow, error)
	// GetMonthlyAmountTransactionSuccess: Retrieves monthly success transaction metrics
	// Purpose: Generate monthly reports of successful transactions for analysis
	// Parameters:
	//   $1: Start date of first comparison period (timestamp)
	//   $2: End date of first comparison period (timestamp)
	//   $3: Start date of second comparison period (timestamp)
	//   $4: End date of second comparison period (timestamp)
	// Returns:
	//   year: Year as text
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   total_success: Count of successful transactions
	//   total_amount: Sum of successful transaction amounts
	// Business Logic:
	//   - Only includes successful (payment_status = 'success') transactions
	//   - Excludes deleted transactions
	//   - Compares two customizable time periods
	//   - Includes gap-filling for months with no transactions
	//   - Returns 0 values for months with no successful transactions
	//   - Orders by most recent year/month first
	GetMonthlyAmountTransactionSuccess(ctx context.Context, arg GetMonthlyAmountTransactionSuccessParams) ([]*GetMonthlyAmountTransactionSuccessRow, error)
	// GetMonthlyAmountTransactionSuccessByMerchant: Retrieves monthly success transaction metrics by merchant_id
	// Purpose: Generate monthly reports of successful transactions for analysis
	// Parameters:
	//   $1: Start date of first comparison period (timestamp)
	//   $2: End date of first comparison period (timestamp)
	//   $3: Start date of second comparison period (timestamp)
	//   $4: End date of second comparison period (timestamp)
	//   $5: Merchant ID
	// Returns:
	//   year: Year as text
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   total_success: Count of successful transactions
	//   total_amount: Sum of successful transaction amounts
	// Business Logic:
	//   - Only includes successful (payment_status = 'success') transactions
	//   - Excludes deleted transactions
	//   - Compares two customizable time periods
	//   - Includes gap-filling for months with no transactions
	//   - Returns 0 values for months with no successful transactions
	//   - Orders by most recent year/month first
	GetMonthlyAmountTransactionSuccessByMerchant(ctx context.Context, arg GetMonthlyAmountTransactionSuccessByMerchantParams) ([]*GetMonthlyAmountTransactionSuccessByMerchantRow, error)
	// GetMonthlyTransactionMethodsByMerchantFailed: Analyzes failed transactions by merchant and payment method monthly
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	// Returns:
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   merchant_id: The merchant identifier
	//   merchant_name: The merchant's name
	//   payment_method: The payment method used
	//   total_transactions: Count of failed transactions
	//   total_amount: Total amount that failed processing
	GetMonthlyTransactionMethodsByMerchantFailed(ctx context.Context, arg GetMonthlyTransactionMethodsByMerchantFailedParams) ([]*GetMonthlyTransactionMethodsByMerchantFailedRow, error)
	// GetMonthlyTransactionMethodsByMerchantSuccess: Analyzes successful transactions by merchant and payment method monthly
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	// Returns:
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   merchant_id: The merchant identifier
	//   merchant_name: The merchant's name
	//   payment_method: The payment method used
	//   total_transactions: Count of successful transactions
	//   total_amount: Total amount processed by this method
	GetMonthlyTransactionMethodsByMerchantSuccess(ctx context.Context, arg GetMonthlyTransactionMethodsByMerchantSuccessParams) ([]*GetMonthlyTransactionMethodsByMerchantSuccessRow, error)
	// GetMonthlyTransactionMethodsFailed: Analyzes failed payment method usage by month
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	// Returns:
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   payment_method: The payment method used
	//   total_transactions: Count of failed transactions
	//   total_amount: Total amount that failed processing
	GetMonthlyTransactionMethodsFailed(ctx context.Context, arg GetMonthlyTransactionMethodsFailedParams) ([]*GetMonthlyTransactionMethodsFailedRow, error)
	// GetMonthlyTransactionMethodsSuccess: Analyzes successful payment method usage by month
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	// Returns:
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   payment_method: The payment method used
	//   total_transactions: Count of successful transactions
	//   total_amount: Total amount processed by this method
	GetMonthlyTransactionMethodsSuccess(ctx context.Context, arg GetMonthlyTransactionMethodsSuccessParams) ([]*GetMonthlyTransactionMethodsSuccessRow, error)
	// GetTransactionByID: Retrieves transaction by transaction ID
	// Purpose: Fetch specific transaction details
	// Parameters:
	//   $1: transaction_id - The unique transaction ID
	// Returns: Full transaction record if active
	// Business Logic:
	//   - Excludes deleted transactions
	//   - Used for transaction details/receipts
	//   - Primary lookup for transaction management
	GetTransactionByID(ctx context.Context, transactionID int32) (*Transaction, error)
	// GetTransactionByMerchant: Retrieves merchant-specific transactions with pagination
	// Purpose: List transactions filtered by merchant ID
	// Parameters:
	//   $1: search_term - Optional text to filter transactions
	//   $2: merchant_id - Optional merchant ID to filter by (NULL for all merchants)
	//   $3: limit - Pagination limit
	//   $4: offset - Pagination offset
	// Returns:
	//   Transaction records with total_count
	// Business Logic:
	//   - Combines merchant filtering with search functionality
	//   - Maintains same sorting and pagination as other transaction queries
	//   - Useful for merchant-specific transaction reporting
	//   - NULL merchant_id parameter returns all merchants' transactions
	GetTransactionByMerchant(ctx context.Context, arg GetTransactionByMerchantParams) ([]*GetTransactionByMerchantRow, error)
	// GetTransactionByOrderID: Retrieves transaction by order reference
	// Purpose: Lookup transaction associated with specific order
	// Parameters:
	//   $1: order_id - The order ID to search by
	// Returns: Transaction record if found and active
	// Business Logic:
	//   - Only returns non-deleted transactions
	//   - Used for order payment verification
	//   - Helps prevent duplicate payments
	GetTransactionByOrderID(ctx context.Context, orderID int32) (*Transaction, error)
	// GetTransactions: Retrieves paginated list of active transactions with search capability
	// Purpose: List all active transactions for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter transactions by payment method or status (NULL for no filter)
	//   $2: limit - Maximum number of records to return (pagination limit)
	//   $3: offset - Number of records to skip (pagination offset)
	// Returns:
	//   All transaction fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted transactions (deleted_at IS NULL)
	//   - Supports partial text matching on payment_method and payment_status fields (case-insensitive)
	//   - Returns newest transactions first (created_at DESC)
	//   - Provides total_count for client-side pagination
	//   - Uses window function COUNT(*) OVER() for efficient total count
	GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]*GetTransactionsRow, error)
	// GetTransactionsActive: Retrieves paginated list of active transactions (identical to GetTransactions)
	// Purpose: Maintains consistent API pattern with other active/trashed endpoints
	// Parameters:
	//   $1: search_term - Optional filter text for payment method/status
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns:
	//   Active transaction records with total_count
	// Business Logic:
	//   - Same functionality as GetTransactions
	//   - Exists for consistency in API design patterns
	// Note: Could be consolidated with GetTransactions if duplicate functionality is undesired
	GetTransactionsActive(ctx context.Context, arg GetTransactionsActiveParams) ([]*GetTransactionsActiveRow, error)
	// GetTransactionsTrashed: Retrieves paginated list of soft-deleted transactions
	// Purpose: View and manage deleted transactions for audit/recovery
	// Parameters:
	//   $1: search_term - Optional text to filter trashed transactions
	//   $2: limit - Maximum records per page
	//   $3: offset - Records to skip
	// Returns:
	//   Trashed transaction records with total_count
	// Business Logic:
	//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
	//   - Maintains same search functionality as active transaction queries
	//   - Preserves chronological sorting (newest first)
	//   - Used in transaction recovery/audit interfaces
	//   - Includes total_count for pagination in trash management UI
	GetTransactionsTrashed(ctx context.Context, arg GetTransactionsTrashedParams) ([]*GetTransactionsTrashedRow, error)
	// GetYearlyAmountTransactionFailed: Retrieves yearly failed transaction metrics
	// Purpose: Generate annual reports of failed transactions
	// Parameters:
	//   $1: Reference year for comparison (current year as integer)
	// Returns:
	//   year: Year as text
	//   total_failed: Count of failed transactions
	//   total_amount: Sum of failed transaction amounts
	// Business Logic:
	//   - Compares current year with previous year automatically
	//   - Only includes failed (payment_status = 'failed') transactions
	//   - Excludes deleted transactions
	//   - Includes gap-filling for years with no transactions
	//   - Returns 0 values for years with no failed transactions
	//   - Orders by most recent year first
	GetYearlyAmountTransactionFailed(ctx context.Context, dollar_1 int32) ([]*GetYearlyAmountTransactionFailedRow, error)
	// GetYearlyAmountTransactionFailedByMerchant: Retrieves yearly failed transaction metrics
	// Purpose: Generate annual reports of failed transactions by merchant_id
	// Parameters:
	//   $1: Reference year for comparison (current year as integer)
	//   $2: Merchant ID
	// Returns:
	//   year: Year as text
	//   total_failed: Count of failed transactions
	//   total_amount: Sum of failed transaction amounts
	// Business Logic:
	//   - Compares current year with previous year automatically
	//   - Only includes failed (payment_status = 'failed') transactions
	//   - Excludes deleted transactions
	//   - Includes gap-filling for years with no transactions
	//   - Returns 0 values for years with no failed transactions
	//   - Orders by most recent year first
	GetYearlyAmountTransactionFailedByMerchant(ctx context.Context, arg GetYearlyAmountTransactionFailedByMerchantParams) ([]*GetYearlyAmountTransactionFailedByMerchantRow, error)
	// GetYearlyAmountTransactionSuccess: Retrieves yearly success transaction metrics
	// Purpose: Generate annual reports of successful transactions
	// Parameters:
	//   $1: Reference year for comparison (current year as integer)
	// Returns:
	//   year: Year as text
	//   total_success: Count of successful transactions
	//   total_amount: Sum of successful transaction amounts
	// Business Logic:
	//   - Compares current year with previous year automatically
	//   - Only includes successful (payment_status = 'success') transactions
	//   - Excludes deleted transactions
	//   - Includes gap-filling for years with no transactions
	//   - Returns 0 values for years with no successful transactions
	//   - Orders by most recent year first
	GetYearlyAmountTransactionSuccess(ctx context.Context, dollar_1 int32) ([]*GetYearlyAmountTransactionSuccessRow, error)
	// GetYearlyAmountTransactionSuccessByMerchant: Retrieves yearly success transaction metrics
	// Purpose: Generate annual reports of successful transactions by merchant_id
	// Parameters:
	//   $1: Reference year for comparison (current year as integer)
	//   $2: Merchant ID
	// Returns:
	//   year: Year as text
	//   total_success: Count of successful transactions
	//   total_amount: Sum of successful transaction amounts
	// Business Logic:
	//   - Compares current year with previous year automatically
	//   - Only includes successful (payment_status = 'success') transactions
	//   - Excludes deleted transactions
	//   - Includes gap-filling for years with no transactions
	//   - Returns 0 values for years with no successful transactions
	//   - Orders by most recent year first
	GetYearlyAmountTransactionSuccessByMerchant(ctx context.Context, arg GetYearlyAmountTransactionSuccessByMerchantParams) ([]*GetYearlyAmountTransactionSuccessByMerchantRow, error)
	// GetYearlyTransactionMethodsByMerchantFailed: Analyzes failed transactions by merchant and payment method yearly
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	// Returns:
	//   year: 4-digit year as text
	//   merchant_id: The merchant identifier
	//   merchant_name: The merchant's name
	//   payment_method: The payment method used
	//   total_transactions: Count of failed transactions
	//   total_amount: Total amount that failed processing
	GetYearlyTransactionMethodsByMerchantFailed(ctx context.Context, arg GetYearlyTransactionMethodsByMerchantFailedParams) ([]*GetYearlyTransactionMethodsByMerchantFailedRow, error)
	// GetYearlyTransactionMethodsByMerchantSuccess: Analyzes successful transactions by merchant and payment method yearly
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	// Returns:
	//   year: 4-digit year as text
	//   merchant_id: The merchant identifier
	//   merchant_name: The merchant's name
	//   payment_method: The payment method used
	//   total_transactions: Count of successful transactions
	//   total_amount: Total amount processed by this method
	GetYearlyTransactionMethodsByMerchantSuccess(ctx context.Context, arg GetYearlyTransactionMethodsByMerchantSuccessParams) ([]*GetYearlyTransactionMethodsByMerchantSuccessRow, error)
	// GetYearlyTransactionMethodsFailed: Analyzes failed payment method usage by year
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	// Returns:
	//   year: 4-digit year as text
	//   payment_method: The payment method used
	//   total_transactions: Count of failed transactions
	//   total_amount: Total amount that failed processing
	GetYearlyTransactionMethodsFailed(ctx context.Context, dollar_1 time.Time) ([]*GetYearlyTransactionMethodsFailedRow, error)
	// GetYearlyTransactionMethodsSuccess: Analyzes successful payment method usage by year
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	// Returns:
	//   year: 4-digit year as text
	//   payment_method: The payment method used
	//   total_transactions: Count of successful transactions
	//   total_amount: Total amount processed by this method
	GetYearlyTransactionMethodsSuccess(ctx context.Context, dollar_1 time.Time) ([]*GetYearlyTransactionMethodsSuccessRow, error)
	// RestoreAllTransactions: Mass restoration of cancelled transactions
	// Purpose: Recover all trashed transactions at once
	// Business Logic:
	//   - Reactivates all soft-deleted transactions
	//   - No parameters needed (bulk operation)
	//   - Typically used during system recovery
	RestoreAllTransactions(ctx context.Context) error
	// RestoreTransaction: Recovers a soft-deleted transaction
	// Purpose: Reactivate a cancelled transaction
	// Parameters:
	//   $1: transaction_id - ID of transaction to restore
	// Returns: The restored transaction record
	// Business Logic:
	//   - Nullifies deleted_at field
	//   - Only works on previously cancelled transactions
	//   - Maintains all original transaction data
	RestoreTransaction(ctx context.Context, transactionID int32) (*Transaction, error)
	// TrashTransaction: Soft-deletes a transaction
	// Purpose: Void/cancel a transaction without permanent deletion
	// Parameters:
	//   $1: transaction_id - ID of transaction to cancel
	// Returns: The soft-deleted transaction record
	// Business Logic:
	//   - Sets deleted_at to current timestamp
	//   - Preserves transaction for reporting
	//   - Only processes active transactions
	//   - Can be restored if needed
	TrashTransaction(ctx context.Context, transactionID int32) (*Transaction, error)
	// UpdateTransaction: Modifies transaction details
	// Purpose: Update transaction information
	// Parameters:
	//   $1: transaction_id - ID of transaction to update
	//   $2: merchant_id - Updated merchant reference
	//   $3: payment_method - Updated payment method
	//   $4: amount - Updated transaction amount
	//   $5: change_amount - Updated change amount
	//   $6: payment_status - Updated payment status
	//   $7: order_id - Updated order reference
	// Returns: Updated transaction record
	// Business Logic:
	//   - Auto-updates updated_at timestamp
	//   - Only modifies active transactions
	//   - Validates all payment fields
	//   - Used for payment corrections/updates
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (*Transaction, error)
}

var _ Querier = (*Queries)(nil)
