// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ConsumerInbox struct {
	ConsumerName       string             `json:"consumer_name"`
	EventKey           string             `json:"event_key"`
	Topic              string             `json:"topic"`
	PartitionID        int32              `json:"partition_id"`
	MessageOffset      int64              `json:"message_offset"`
	Status             string             `json:"status"`
	Attempts           int32              `json:"attempts"`
	LeaseUntil         pgtype.Timestamptz `json:"lease_until"`
	LastError          string             `json:"last_error"`
	ProcessedAt        pgtype.Timestamptz `json:"processed_at"`
	ReservationVersion int64              `json:"reservation_version"`
}
