// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// MarkConsumerInboxProcessed: Completes only the active reservation.
	MarkConsumerInboxProcessed(ctx context.Context, arg MarkConsumerInboxProcessedParams) error
	// ReleaseConsumerInbox: Releases only the active reservation.
	ReleaseConsumerInbox(ctx context.Context, arg ReleaseConsumerInboxParams) error
	// ReserveConsumerInbox: Claims an event and returns whether this call owns the reservation.
	ReserveConsumerInbox(ctx context.Context, arg ReserveConsumerInboxParams) (*ReserveConsumerInboxRow, error)
}

var _ Querier = (*Queries)(nil)
