// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	// CreateCategory: Inserts a new category into the system
	// Purpose: Adds a new product category for classification and reporting
	// Parameters:
	//   $1: Category name
	//   $2: Category description
	//   $3: Slug for category (URL-friendly identifier)
	// Returns:
	//   Full category record including generated ID
	// Business Logic:
	//   - Assumes unique slug for identification in URLs
	//   - Automatically populates timestamps via default DB behavior (if configured)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (*Category, error)
	// DeleteAllPermanentCategories: Permanently deletes all trashed categories
	// Purpose: Bulk purge of all soft-deleted category records
	// Parameters: None
	// Returns: None
	// Business Logic:
	//   - Only affects records marked as deleted
	DeleteAllPermanentCategories(ctx context.Context) error
	// DeleteCategoryPermanently: Removes a soft-deleted category permanently
	// Purpose: Final cleanup of trashed categories
	// Parameters:
	//   $1: Category ID
	// Returns:
	//   Nothing (command only)
	// Business Logic:
	//   - Ensures category is deleted only if it has been soft-deleted
	DeleteCategoryPermanently(ctx context.Context, categoryID int32) error
	// GetCategories: Retrieves paginated list of active categories with search capability
	// Purpose: List all active product categories for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter categories by name or slug (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All category fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted categories (deleted_at IS NULL)
	//   - Supports partial text matching on name and slug_category fields (case-insensitive)
	//   - Returns newest categories first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]*GetCategoriesRow, error)
	// GetCategoriesActive: Retrieves paginated list of active categories with search capability
	// Purpose: List all active product categories for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter categories by name or slug (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All category fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted categories (deleted_at IS NULL)
	//   - Supports partial text matching on name and slug_category fields (case-insensitive)
	//   - Returns newest categories first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetCategoriesActive(ctx context.Context, arg GetCategoriesActiveParams) ([]*GetCategoriesActiveRow, error)
	// GetCategoriesTrashed: Retrieves paginated list of soft-deleted categories
	// Purpose: View/manage deleted categories for potential restoration
	// Parameters:
	//   $1: search_term - Optional filter text (NULL for all trashed categories)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns:
	//   Trashed category records with total_count
	// Business Logic:
	//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
	//   - Same search functionality as active categories
	//   - Maintains consistent sorting with active records
	//   - Used in trash management/recovery interfaces
	GetCategoriesTrashed(ctx context.Context, arg GetCategoriesTrashedParams) ([]*GetCategoriesTrashedRow, error)
	// GetCategoryByID: Fetches a single category by its ID
	// Purpose: Retrieve details of an active (non-deleted) category
	// Parameters:
	//   $1: Category ID to search for
	// Returns:
	//   Full category record if found and not deleted
	// Business Logic:
	//   - Excludes soft-deleted categories
	GetCategoryByID(ctx context.Context, categoryID int32) (*Category, error)
	// GetCategoryByIDTrashed: Fetches a single category by its ID
	// Purpose: Retrieve details of an active (non-deleted) category
	// Parameters:
	//   $1: Category ID to search for
	// Returns:
	//   Full category record if found and not deleted
	// Business Logic:
	//   - Excludes soft-deleted categories
	GetCategoryByIDTrashed(ctx context.Context, categoryID int32) (*Category, error)
	// GetCategoryByName: Fetches a single category by its name
	// Purpose: Retrieve details of an active (non-deleted) category
	// Parameters:
	//   $1: Category name to search for
	// Returns:
	//   Full category record if found and not deleted
	// Business Logic:
	//   - Excludes soft-deleted categories
	GetCategoryByName(ctx context.Context, name string) (*Category, error)
	// GetCategoryByNameAndId: Fetches a single category by its name and id
	// Purpose: Retrieve details of an active (non-deleted) category
	// Parameters:
	//   $1: Category name or id to search for
	// Returns:
	//   Full category record if found and not deleted
	// Business Logic:
	//   - Excludes soft-deleted categories
	GetCategoryByNameAndId(ctx context.Context, arg GetCategoryByNameAndIdParams) (*Category, error)
	// GetMonthlyCategory: Retrieves monthly sales activity for all categories within a 1-year period
	// Purpose: Provides category performance metrics by month for operational analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	// Returns:
	//   category_id: Unique identifier for the category
	//   category_name: Display name of the category
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   order_count: Number of orders associated with the category
	//   items_sold: Total quantity of items sold from the category
	//   total_revenue: Total revenue generated from category items
	// Business Logic:
	//   - Analyzes a rolling 12-month period from the reference date
	//   - Excludes deleted orders, items, products, and categories to ensure valid data
	//   - Aggregates by category and month for trend tracking
	//   - Uses abbreviated month names for compact visual reporting
	//   - Results sorted by month and revenue for time-series analysis
	GetMonthlyCategory(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyCategoryRow, error)
	// GetMonthlyCategoryById: Retrieves monthly sales activity for all categories within a 1-year period by category_id
	// Purpose: Provides category performance metrics by month for operational analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	//   $2: Category ID
	// Returns:
	//   category_id: Unique identifier for the category
	//   category_name: Display name of the category
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   order_count: Number of orders associated with the category
	//   items_sold: Total quantity of items sold from the category
	//   total_revenue: Total revenue generated from category items
	// Business Logic:
	//   - Analyzes a rolling 12-month period from the reference date
	//   - Excludes deleted orders, items, products, and categories to ensure valid data
	//   - Aggregates by category and month for trend tracking
	//   - Uses abbreviated month names for compact visual reporting
	//   - Results sorted by month and revenue for time-series analysis
	GetMonthlyCategoryById(ctx context.Context, arg GetMonthlyCategoryByIdParams) ([]*GetMonthlyCategoryByIdRow, error)
	// GetMonthlyCategoryByMerchant: Retrieves monthly sales activity for all categories within a 1-year period by merchant_id
	// Purpose: Provides category performance metrics by month for operational analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	//   $2: Merchant ID
	// Returns:
	//   category_id: Unique identifier for the category
	//   category_name: Display name of the category
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   order_count: Number of orders associated with the category
	//   items_sold: Total quantity of items sold from the category
	//   total_revenue: Total revenue generated from category items
	// Business Logic:
	//   - Analyzes a rolling 12-month period from the reference date
	//   - Excludes deleted orders, items, products, and categories to ensure valid data
	//   - Aggregates by category and month for trend tracking
	//   - Uses abbreviated month names for compact visual reporting
	//   - Results sorted by month and revenue for time-series analysis
	GetMonthlyCategoryByMerchant(ctx context.Context, arg GetMonthlyCategoryByMerchantParams) ([]*GetMonthlyCategoryByMerchantRow, error)
	// GetMonthlyTotalPrice: Retrieves monthly revenue totals across two comparison periods
	// Purpose: Provides month-over-month revenue analytics for financial reporting
	// Parameters:
	//   $1: Start date of first comparison period
	//   $2: End date of first comparison period
	//   $3: Start date of second comparison period
	//   $4: End date of second comparison period
	// Returns:
	//   year: Year of revenue data (text format)
	//   month_name: Full month name (e.g. "January")
	//   total_revenue: Sum of order totals for that month (0 if no sales)
	// Business Logic:
	//   - Compares revenue between two customizable date ranges
	//   - Joins with order_items to ensure accurate order calculations
	//   - Excludes deleted orders and order items for data integrity
	//   - Uses gap-filling to show all months in both periods
	//   - Formats output for financial dashboards
	GetMonthlyTotalPrice(ctx context.Context, arg GetMonthlyTotalPriceParams) ([]*GetMonthlyTotalPriceRow, error)
	// GetMonthlyTotalPriceById: Retrieves monthly revenue totals across two comparison periods by category_id
	// Purpose: Provides month-over-month revenue analytics for financial reporting
	// Parameters:
	//   $1: Start date of first comparison period
	//   $2: End date of first comparison period
	//   $3: Start date of second comparison period
	//   $4: End date of second comparison period
	//   $5: Category ID
	// Returns:
	//   year: Year of revenue data (text format)
	//   month_name: Full month name (e.g. "January")
	//   total_revenue: Sum of order totals for that month (0 if no sales)
	// Business Logic:
	//   - Compares revenue between two customizable date ranges
	//   - Joins with order_items to ensure accurate order calculations
	//   - Excludes deleted orders and order items for data integrity
	//   - Uses gap-filling to show all months in both periods
	//   - Formats output for financial dashboards
	GetMonthlyTotalPriceById(ctx context.Context, arg GetMonthlyTotalPriceByIdParams) ([]*GetMonthlyTotalPriceByIdRow, error)
	// GetMonthlyTotalPriceByMerchant: Retrieves monthly revenue totals across two comparison periods by merchant_id
	// Purpose: Provides month-over-month revenue analytics for financial reporting
	// Parameters:
	//   $1: Start date of first comparison period
	//   $2: End date of first comparison period
	//   $3: Start date of second comparison period
	//   $4: End date of second comparison period
	//   $5: Merchant ID
	// Returns:
	//   year: Year of revenue data (text format)
	//   month_name: Full month name (e.g. "January")
	//   total_revenue: Sum of order totals for that month (0 if no sales)
	// Business Logic:
	//   - Compares revenue between two customizable date ranges
	//   - Joins with order_items to ensure accurate order calculations
	//   - Excludes deleted orders and order items for data integrity
	//   - Uses gap-filling to show all months in both periods
	//   - Formats output for financial dashboards
	GetMonthlyTotalPriceByMerchant(ctx context.Context, arg GetMonthlyTotalPriceByMerchantParams) ([]*GetMonthlyTotalPriceByMerchantRow, error)
	// GetYearlyCategory: Retrieves annual sales performance for categories over a 5-year span
	// Purpose: Enables long-term product category performance trend analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	// Returns:
	//   year: 4-digit year as text
	//   category_id: Unique category identifier
	//   category_name: Display name of the category
	//   order_count: Annual number of orders involving this category
	//   items_sold: Quantity of products sold from this category
	//   total_revenue: Total sales revenue from category products
	//   unique_products_sold: Count of unique products sold within the category
	// Business Logic:
	//   - Covers the current year and previous four years (5-year window)
	//   - Filters out soft-deleted data from all related tables
	//   - Provides both volume and value metrics for category-level evaluation
	//   - Results sorted by year and revenue to show historical trends
	//   - Suitable for business reviews and strategic category planning
	GetYearlyCategory(ctx context.Context, dollar_1 time.Time) ([]*GetYearlyCategoryRow, error)
	// GetYearlyCategoryById: Retrieves annual sales performance for categories over a 5-year span by category_id
	// Purpose: Enables long-term product category performance trend analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	//   $2: Category ID
	// Returns:
	//   year: 4-digit year as text
	//   category_id: Unique category identifier
	//   category_name: Display name of the category
	//   order_count: Annual number of orders involving this category
	//   items_sold: Quantity of products sold from this category
	//   total_revenue: Total sales revenue from category products
	//   unique_products_sold: Count of unique products sold within the category
	// Business Logic:
	//   - Covers the current year and previous four years (5-year window)
	//   - Filters out soft-deleted data from all related tables
	//   - Provides both volume and value metrics for category-level evaluation
	//   - Results sorted by year and revenue to show historical trends
	//   - Suitable for business reviews and strategic category planning
	GetYearlyCategoryById(ctx context.Context, arg GetYearlyCategoryByIdParams) ([]*GetYearlyCategoryByIdRow, error)
	// GetYearlyCategoryByMerchant: Retrieves annual sales performance for categories over a 5-year span by merchant_id
	// Purpose: Enables long-term product category performance trend analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	//   $2: Merchant ID
	// Returns:
	//   year: 4-digit year as text
	//   category_id: Unique category identifier
	//   category_name: Display name of the category
	//   order_count: Annual number of orders involving this category
	//   items_sold: Quantity of products sold from this category
	//   total_revenue: Total sales revenue from category products
	//   unique_products_sold: Count of unique products sold within the category
	// Business Logic:
	//   - Covers the current year and previous four years (5-year window)
	//   - Filters out soft-deleted data from all related tables
	//   - Provides both volume and value metrics for category-level evaluation
	//   - Results sorted by year and revenue to show historical trends
	//   - Suitable for business reviews and strategic category planning
	GetYearlyCategoryByMerchant(ctx context.Context, arg GetYearlyCategoryByMerchantParams) ([]*GetYearlyCategoryByMerchantRow, error)
	// GetYearlyTotalPrice: Retrieves annual revenue with category/product validation
	// Purpose: Provides year-over-year revenue analysis with product hierarchy verification
	// Parameters:
	//   $1: Reference year for comparison (current year)
	// Returns:
	//   year: Year as text
	//   total_revenue: Annual revenue total (0 if no sales)
	// Business Logic:
	//   - Compares current year with previous year automatically
	//   - Validates product/category relationships through joins
	//   - Excludes deleted records across all joined tables
	//   - Ensures complete year reporting even with no sales
	//   - Orders results by most recent year first
	GetYearlyTotalPrice(ctx context.Context, dollar_1 int32) ([]*GetYearlyTotalPriceRow, error)
	// GetYearlyTotalPriceById: Retrieves annual revenue with category/product validation by category_id
	// Purpose: Provides year-over-year revenue analysis with product hierarchy verification
	// Parameters:
	//   $1: Reference year for comparison (current year)
	//   $2: Category ID
	// Returns:
	//   year: Year as text
	//   total_revenue: Annual revenue total (0 if no sales)
	// Business Logic:
	//   - Compares current year with previous year automatically
	//   - Validates product/category relationships through joins
	//   - Excludes deleted records across all joined tables
	//   - Ensures complete year reporting even with no sales
	//   - Orders results by most recent year first
	GetYearlyTotalPriceById(ctx context.Context, arg GetYearlyTotalPriceByIdParams) ([]*GetYearlyTotalPriceByIdRow, error)
	// GetYearlyTotalPriceByMerchant: Retrieves annual revenue with category/product validation by merchant_id
	// Purpose: Provides year-over-year revenue analysis with product hierarchy verification
	// Parameters:
	//   $1: Reference year for comparison (current year)
	//   $2: Merchant ID
	// Returns:
	//   year: Year as text
	//   total_revenue: Annual revenue total (0 if no sales)
	// Business Logic:
	//   - Compares current year with previous year automatically
	//   - Validates product/category relationships through joins
	//   - Excludes deleted records across all joined tables
	//   - Ensures complete year reporting even with no sales
	//   - Orders results by most recent year first
	GetYearlyTotalPriceByMerchant(ctx context.Context, arg GetYearlyTotalPriceByMerchantParams) ([]*GetYearlyTotalPriceByMerchantRow, error)
	// RestoreAllCategories: Recovers all trashed categories
	// Purpose: Bulk restore of all soft-deleted category records
	// Parameters: None
	// Returns: None
	// Business Logic:
	//   - Resets deleted_at for all soft-deleted records
	RestoreAllCategories(ctx context.Context) error
	// RestoreCategory: Recovers a previously trashed category
	// Purpose: Restores a soft-deleted category for reuse
	// Parameters:
	//   $1: Category ID
	// Returns:
	//   Restored category record
	// Business Logic:
	//   - Only applies to categories currently marked as deleted
	RestoreCategory(ctx context.Context, categoryID int32) (*Category, error)
	// TrashCategory: Soft-deletes a category
	// Purpose: Moves category to trash without permanent deletion
	// Parameters:
	//   $1: Category ID
	// Returns:
	//   The soft-deleted category record
	// Business Logic:
	//   - Updates deleted_at with current timestamp
	//   - Prevents repeat trashing of already-deleted records
	TrashCategory(ctx context.Context, categoryID int32) (*Category, error)
	// UpdateCategory: Updates category details
	// Purpose: Modify existing category data while maintaining soft delete integrity
	// Parameters:
	//   $1: Category ID
	//   $2: Updated name
	//   $3: Updated description
	//   $4: Updated slug
	// Returns:
	//   Updated category record
	// Business Logic:
	//   - Automatically updates the updated_at field
	//   - Skips if category has been soft-deleted
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*Category, error)
}

var _ Querier = (*Queries)(nil)
