// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	OrderID    int32            `json:"order_id"`
	MerchantID int32            `json:"merchant_id"`
	CashierID  int32            `json:"cashier_id"`
	TotalPrice int64            `json:"total_price"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type OrderItem struct {
	OrderItemID int32            `json:"order_item_id"`
	OrderID     int32            `json:"order_id"`
	ProductID   int32            `json:"product_id"`
	Quantity    int32            `json:"quantity"`
	Price       int32            `json:"price"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type Product struct {
	ProductID    int32            `json:"product_id"`
	MerchantID   int32            `json:"merchant_id"`
	CategoryID   int32            `json:"category_id"`
	Name         string           `json:"name"`
	Description  *string          `json:"description"`
	Price        int32            `json:"price"`
	CountInStock int32            `json:"count_in_stock"`
	Brand        *string          `json:"brand"`
	Weight       *int32           `json:"weight"`
	SlugProduct  *string          `json:"slug_product"`
	ImageProduct *string          `json:"image_product"`
	Barcode      *string          `json:"barcode"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}
