// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	// CreateCategory: Inserts a new category into the system
	// Purpose: Adds a new product category for classification and reporting
	// Parameters:
	//   $1: Category name
	//   $2: Category description
	//   $3: Slug for category (URL-friendly identifier)
	// Returns:
	//   Full category record including generated ID
	// Business Logic:
	//   - Assumes unique slug for identification in URLs
	//   - Automatically populates timestamps via default DB behavior (if configured)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (*Category, error)
	// CreateMerchant: Creates a new merchant account
	// Purpose: Register a new merchant in the system
	// Parameters:
	//   $1: user_id - Associated user account ID
	//   $2: name - Business name
	//   $3: description - Business description
	//   $4: address - Physical address
	//   $5: contact_email - Business email
	//   $6: contact_phone - Business phone
	//   $7: status - Account status (active/inactive)
	// Returns: The created merchant record
	// Business Logic:
	//   - Sets created_at timestamp automatically
	//   - Requires all mandatory merchant fields
	//   - Status defaults to 'active' unless specified otherwise
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (*Merchant, error)
	// CreateProduct: Creates a new product record
	// Purpose: Add a new product to inventory
	// Parameters:
	//   $1: merchant_id - Merchant who owns the product
	//   $2: category_id - Product category
	//   $3: name - Product name
	//   $4: description - Detailed description
	//   $5: price - Selling price
	//   $6: count_in_stock - Inventory quantity
	//   $7: brand - Manufacturer brand
	//   $8: weight - Product weight
	//   $9: slug_product - URL-friendly identifier
	//   $10: image_product - Image URL/path
	//   $11: barcode - Product barcode
	// Returns: Complete created product record
	// Business Logic:
	//   - Sets created_at automatically
	//   - Validates required fields
	//   - Initializes inventory tracking
	CreateProduct(ctx context.Context, arg CreateProductParams) (*Product, error)
	// DecrementProductCountStock: Atomically decrements product stock
	// Purpose: Safe inventory decrement with optimistic concurrency guard
	// Parameters:
	//   $1: product_id - Product to update
	//   $2: quantity - Amount to subtract from current stock
	// Returns: Updated product record
	// Business Logic:
	//   - Atomic decrement (no lost update between read and write)
	//   - Refuses to go below zero: WHERE count_in_stock >= $2
	//   - Returns zero rows when stock is insufficient (caller maps to 400)
	DecrementProductCountStock(ctx context.Context, arg DecrementProductCountStockParams) (*Product, error)
	// DeleteAllPermanentCategories: Permanently deletes all trashed categories
	// Purpose: Bulk purge of all soft-deleted category records
	// Parameters: None
	// Returns: None
	// Business Logic:
	//   - Only affects records marked as deleted
	DeleteAllPermanentCategories(ctx context.Context) error
	// DeleteAllPermanentMerchants: Purges all trashed merchants
	// Purpose: Clean up all soft-deleted merchant records
	// Business Logic:
	//   - Irreversible bulk deletion operation
	//   - Only affects already soft-deleted records
	//   - Typically used during database maintenance
	//   - Should be restricted to admin users
	DeleteAllPermanentMerchants(ctx context.Context) error
	// DeleteAllPermanentProducts: Purges all trashed products
	// Purpose: Clean up deleted products
	// Business Logic:
	//   - Bulk permanent deletion
	//   - Database maintenance operation
	DeleteAllPermanentProducts(ctx context.Context) error
	// DeleteCategoryPermanently: Removes a soft-deleted category permanently
	// Purpose: Final cleanup of trashed categories
	// Parameters:
	//   $1: Category ID
	// Returns:
	//   Nothing (command only)
	// Business Logic:
	//   - Ensures category is deleted only if it has been soft-deleted
	DeleteCategoryPermanently(ctx context.Context, categoryID int32) error
	// DeleteMerchantPermanently: Hard-deletes a merchant
	// Purpose: Completely remove merchant from database
	// Parameters:
	//   $1: merchant_id - ID of merchant to delete
	// Business Logic:
	//   - Permanent deletion of already soft-deleted records
	//   - No return value (exec-only operation)
	//   - Irreversible action - use with caution
	//   - Should trigger cleanup of related records
	DeleteMerchantPermanently(ctx context.Context, merchantID int32) error
	// DeleteProductPermanently: Hard-deletes a product
	// Purpose: Completely remove product record
	// Parameters:
	//   $1: product_id - Product to delete
	// Business Logic:
	//   - Permanent deletion
	//   - Only affects already trashed products
	//   - Irreversible operation
	DeleteProductPermanently(ctx context.Context, productID int32) error
	// GetCategories: Retrieves paginated list of active categories with search capability
	// Purpose: List all active product categories for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter categories by name or slug (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All category fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted categories (deleted_at IS NULL)
	//   - Supports partial text matching on name and slug_category fields (case-insensitive)
	//   - Returns newest categories first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]*GetCategoriesRow, error)
	// GetCategoriesActive: Retrieves paginated list of active categories with search capability
	// Purpose: List all active product categories for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter categories by name or slug (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All category fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted categories (deleted_at IS NULL)
	//   - Supports partial text matching on name and slug_category fields (case-insensitive)
	//   - Returns newest categories first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetCategoriesActive(ctx context.Context, arg GetCategoriesActiveParams) ([]*GetCategoriesActiveRow, error)
	// GetCategoriesTrashed: Retrieves paginated list of soft-deleted categories
	// Purpose: View/manage deleted categories for potential restoration
	// Parameters:
	//   $1: search_term - Optional filter text (NULL for all trashed categories)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns:
	//   Trashed category records with total_count
	// Business Logic:
	//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
	//   - Same search functionality as active categories
	//   - Maintains consistent sorting with active records
	//   - Used in trash management/recovery interfaces
	GetCategoriesTrashed(ctx context.Context, arg GetCategoriesTrashedParams) ([]*GetCategoriesTrashedRow, error)
	// GetCategoryByID: Fetches a single category by its ID
	// Purpose: Retrieve details of an active (non-deleted) category
	// Parameters:
	//   $1: Category ID to search for
	// Returns:
	//   Full category record if found and not deleted
	// Business Logic:
	//   - Excludes soft-deleted categories
	GetCategoryByID(ctx context.Context, categoryID int32) (*Category, error)
	// GetCategoryByIDTrashed: Fetches a single category by its ID
	// Purpose: Retrieve details of an active (non-deleted) category
	// Parameters:
	//   $1: Category ID to search for
	// Returns:
	//   Full category record if found and not deleted
	// Business Logic:
	//   - Excludes soft-deleted categories
	GetCategoryByIDTrashed(ctx context.Context, categoryID int32) (*Category, error)
	// GetCategoryByName: Fetches a single category by its name
	// Purpose: Retrieve details of an active (non-deleted) category
	// Parameters:
	//   $1: Category name to search for
	// Returns:
	//   Full category record if found and not deleted
	// Business Logic:
	//   - Excludes soft-deleted categories
	GetCategoryByName(ctx context.Context, name string) (*Category, error)
	// GetCategoryByNameAndId: Fetches a single category by its name and id
	// Purpose: Retrieve details of an active (non-deleted) category
	// Parameters:
	//   $1: Category name or id to search for
	// Returns:
	//   Full category record if found and not deleted
	// Business Logic:
	//   - Excludes soft-deleted categories
	GetCategoryByNameAndId(ctx context.Context, arg GetCategoryByNameAndIdParams) (*Category, error)
	// GetMerchantByID: Retrieves active merchant by ID
	// Purpose: Fetch merchant details for display/editing
	// Parameters:
	//   $1: merchant_id - ID of merchant to retrieve
	// Returns: Full merchant record if found and active
	// Business Logic:
	//   - Excludes soft-deleted records
	//   - Returns single record or nothing
	//   - Used for merchant profile viewing and editing
	GetMerchantByID(ctx context.Context, merchantID int32) (*Merchant, error)
	// GetMerchants: Retrieves paginated list of active merchants with search capability
	// Purpose: List all active merchants for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter merchants by name or email (NULL for no filter)
	//   $2: limit - Maximum number of records to return (pagination limit)
	//   $3: offset - Number of records to skip (pagination offset)
	// Returns:
	//   All merchant fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted merchants (deleted_at IS NULL)
	//   - Supports partial text matching on name and contact_email fields (case-insensitive ILIKE)
	//   - Returns newest merchants first (created_at DESC)
	//   - Provides total_count for client-side pagination calculations
	//   - Uses window function COUNT(*) OVER() for efficient total count
	GetMerchants(ctx context.Context, arg GetMerchantsParams) ([]*GetMerchantsRow, error)
	// GetMerchantsActive: Retrieves paginated list of active merchants (identical to GetMerchants)
	// Purpose: Maintains consistent API pattern with other active/trashed endpoints
	// Parameters:
	//   $1: search_term - Optional filter text for name/email
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns:
	//   Active merchant records with total_count
	// Business Logic:
	//   - Same functionality as GetMerchants
	//   - Exists for consistency in API design patterns
	// Note: Could be consolidated with GetMerchants if duplicate functionality is undesired
	GetMerchantsActive(ctx context.Context, arg GetMerchantsActiveParams) ([]*GetMerchantsActiveRow, error)
	// GetMerchantsTrashed: Retrieves paginated list of soft-deleted merchants
	// Purpose: View and manage deleted merchants for potential restoration
	// Parameters:
	//   $1: search_term - Optional text to filter trashed merchants
	//   $2: limit - Maximum records per page
	//   $3: offset - Records to skip
	// Returns:
	//   Trashed merchant records with total_count
	// Business Logic:
	//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
	//   - Maintains same search functionality as active merchant queries
	//   - Preserves chronological sorting (newest first)
	//   - Used in merchant recovery/audit interfaces
	//   - Includes total_count for pagination in trash management UI
	GetMerchantsTrashed(ctx context.Context, arg GetMerchantsTrashedParams) ([]*GetMerchantsTrashedRow, error)
	// GetMonthlyCategory: Retrieves monthly sales activity for all categories within a 1-year period
	// Purpose: Provides category performance metrics by month for operational analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	// Returns:
	//   category_id: Unique identifier for the category
	//   category_name: Display name of the category
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   order_count: Number of orders associated with the category
	//   items_sold: Total quantity of items sold from the category
	//   total_revenue: Total revenue generated from category items
	// Business Logic:
	//   - Analyzes a rolling 12-month period from the reference date
	//   - Excludes deleted orders, items, products, and categories to ensure valid data
	//   - Aggregates by category and month for trend tracking
	//   - Uses abbreviated month names for compact visual reporting
	//   - Results sorted by month and revenue for time-series analysis
	GetMonthlyCategory(ctx context.Context, dollar_1 time.Time) ([]*GetMonthlyCategoryRow, error)
	// GetMonthlyCategoryById: Retrieves monthly sales activity for all categories within a 1-year period by category_id
	// Purpose: Provides category performance metrics by month for operational analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	//   $2: Category ID
	// Returns:
	//   category_id: Unique identifier for the category
	//   category_name: Display name of the category
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   order_count: Number of orders associated with the category
	//   items_sold: Total quantity of items sold from the category
	//   total_revenue: Total revenue generated from category items
	// Business Logic:
	//   - Analyzes a rolling 12-month period from the reference date
	//   - Excludes deleted orders, items, products, and categories to ensure valid data
	//   - Aggregates by category and month for trend tracking
	//   - Uses abbreviated month names for compact visual reporting
	//   - Results sorted by month and revenue for time-series analysis
	GetMonthlyCategoryById(ctx context.Context, arg GetMonthlyCategoryByIdParams) ([]*GetMonthlyCategoryByIdRow, error)
	// GetMonthlyCategoryByMerchant: Retrieves monthly sales activity for all categories within a 1-year period by merchant_id
	// Purpose: Provides category performance metrics by month for operational analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 12-month analysis period
	//   $2: Merchant ID
	// Returns:
	//   category_id: Unique identifier for the category
	//   category_name: Display name of the category
	//   month: 3-letter month abbreviation (e.g. 'Jan')
	//   order_count: Number of orders associated with the category
	//   items_sold: Total quantity of items sold from the category
	//   total_revenue: Total revenue generated from category items
	// Business Logic:
	//   - Analyzes a rolling 12-month period from the reference date
	//   - Excludes deleted orders, items, products, and categories to ensure valid data
	//   - Aggregates by category and month for trend tracking
	//   - Uses abbreviated month names for compact visual reporting
	//   - Results sorted by month and revenue for time-series analysis
	GetMonthlyCategoryByMerchant(ctx context.Context, arg GetMonthlyCategoryByMerchantParams) ([]*GetMonthlyCategoryByMerchantRow, error)
	// GetMonthlyTotalPrice: Retrieves monthly revenue totals across two comparison periods
	// Purpose: Provides month-over-month revenue analytics for financial reporting
	// Parameters:
	//   $1: Start date of first comparison period
	//   $2: End date of first comparison period
	//   $3: Start date of second comparison period
	//   $4: End date of second comparison period
	// Returns:
	//   year: Year of revenue data (text format)
	//   month_name: Full month name (e.g. "January")
	//   total_revenue: Sum of order totals for that month (0 if no sales)
	// Business Logic:
	//   - Compares revenue between two customizable date ranges
	//   - Joins with order_items to ensure accurate order calculations
	//   - Excludes deleted orders and order items for data integrity
	//   - Uses gap-filling to show all months in both periods
	//   - Formats output for financial dashboards
	GetMonthlyTotalPrice(ctx context.Context, arg GetMonthlyTotalPriceParams) ([]*GetMonthlyTotalPriceRow, error)
	// GetMonthlyTotalPriceById: Retrieves monthly revenue totals across two comparison periods by category_id
	// Purpose: Provides month-over-month revenue analytics for financial reporting
	// Parameters:
	//   $1: Start date of first comparison period
	//   $2: End date of first comparison period
	//   $3: Start date of second comparison period
	//   $4: End date of second comparison period
	//   $5: Category ID
	// Returns:
	//   year: Year of revenue data (text format)
	//   month_name: Full month name (e.g. "January")
	//   total_revenue: Sum of order totals for that month (0 if no sales)
	// Business Logic:
	//   - Compares revenue between two customizable date ranges
	//   - Joins with order_items to ensure accurate order calculations
	//   - Excludes deleted orders and order items for data integrity
	//   - Uses gap-filling to show all months in both periods
	//   - Formats output for financial dashboards
	GetMonthlyTotalPriceById(ctx context.Context, arg GetMonthlyTotalPriceByIdParams) ([]*GetMonthlyTotalPriceByIdRow, error)
	// GetMonthlyTotalPriceByMerchant: Retrieves monthly revenue totals across two comparison periods by merchant_id
	// Purpose: Provides month-over-month revenue analytics for financial reporting
	// Parameters:
	//   $1: Start date of first comparison period
	//   $2: End date of first comparison period
	//   $3: Start date of second comparison period
	//   $4: End date of second comparison period
	//   $5: Merchant ID
	// Returns:
	//   year: Year of revenue data (text format)
	//   month_name: Full month name (e.g. "January")
	//   total_revenue: Sum of order totals for that month (0 if no sales)
	// Business Logic:
	//   - Compares revenue between two customizable date ranges
	//   - Joins with order_items to ensure accurate order calculations
	//   - Excludes deleted orders and order items for data integrity
	//   - Uses gap-filling to show all months in both periods
	//   - Formats output for financial dashboards
	GetMonthlyTotalPriceByMerchant(ctx context.Context, arg GetMonthlyTotalPriceByMerchantParams) ([]*GetMonthlyTotalPriceByMerchantRow, error)
	// GetProductByID: Retrieves active product by ID
	// Purpose: Fetch product details for display/purchase
	// Parameters:
	//   $1: product_id - ID of product to retrieve
	// Returns: Full product record if active
	// Business Logic:
	//   - Excludes deleted products
	//   - Used for product pages and checkout
	GetProductByID(ctx context.Context, productID int32) (*Product, error)
	// GetProductByIdTrashed: Retrieves product including deleted
	// Purpose: View deleted products for restoration
	// Parameters:
	//   $1: product_id - ID of product to retrieve
	// Returns: Product record regardless of deletion status
	// Business Logic:
	//   - Bypasses deleted_at filter
	//   - Used in admin/recovery interfaces
	GetProductByIdTrashed(ctx context.Context, productID int32) (*Product, error)
	// GetProducts: Retrieves paginated list of active products with search capability
	// Purpose: List all active (non-deleted) products for display in UI
	// Parameters:
	//   $1: search_term - Optional text to filter products (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All product fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted products (deleted_at IS NULL)
	//   - Supports partial, case-insensitive search on name, description, brand, slug, and barcode
	//   - Orders results by newest first (created_at DESC)
	//   - Uses COUNT(*) OVER() to include total matching record count for pagination UI
	GetProducts(ctx context.Context, arg GetProductsParams) ([]*GetProductsRow, error)
	// GetProductsActive: Retrieves paginated list of active products (duplicate of GetProducts)
	// Purpose: Explicitly return active (non-deleted) products with search capability
	// Parameters:
	//   $1: search_term - Optional text to filter products (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All product fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted products (deleted_at IS NULL)
	//   - Supports partial, case-insensitive search on name, description, brand, slug, and barcode
	//   - Ordered by newest first (created_at DESC)
	//   - Useful if frontend/backend wants clearer distinction in naming
	GetProductsActive(ctx context.Context, arg GetProductsActiveParams) ([]*GetProductsActiveRow, error)
	// GetProductsByCategoryName: Retrieves paginated and filtered products under a specific category name
	// Purpose: Display products by category for customers or category-focused pages
	// Parameters:
	//   $1: category_name - The name of the category to filter by
	//   $2: search_term - Optional text to filter by product name or description
	//   $3: min_price - Minimum price filter (0 to ignore)
	//   $4: max_price - Maximum price filter (0 to ignore, defaults to very high value)
	//   $5: limit - Number of products to return (pagination)
	//   $6: offset - Number of products to skip (pagination)
	// Returns:
	//   - Filtered list of product fields including category name
	//   - total_count of all matching products for pagination UI
	// Business Logic:
	//   - Excludes soft-deleted products (deleted_at IS NULL)
	//   - Matches category name exactly
	//   - Supports case-insensitive partial search on name and description
	//   - Filters by category ID only if provided
	//   - Filters by price range only if values provided
	//   - Ordered by newest products first (created_at DESC)
	GetProductsByCategoryName(ctx context.Context, arg GetProductsByCategoryNameParams) ([]*GetProductsByCategoryNameRow, error)
	// GetProductsByMerchant: Retrieves paginated and filtered products owned by a specific merchant
	// Purpose: Allow merchants to view and manage their own products with advanced filtering options
	// Parameters:
	//   $1: merchant_id - Filter products belonging to this merchant
	//   $2: search_term - Optional text to filter by product name or description
	//   $3: category_id - Optional category filter (0 or NULL to ignore)
	//   $4: min_price - Minimum price filter (0 to ignore)
	//   $5: max_price - Maximum price filter (0 to ignore, defaults to very high value)
	//   $6: limit - Number of products to return (pagination)
	//   $7: offset - Number of products to skip (pagination)
	// Returns:
	//   - Filtered list of product fields including category name
	//   - total_count of all matching products for pagination UI
	// Business Logic:
	//   - Excludes soft-deleted products (deleted_at IS NULL)
	//   - Supports case-insensitive partial search on name and description
	//   - Filters by category ID only if provided
	//   - Filters by price range only if values provided (>= min_price and <= max_price)
	//   - Ordered by newest products first (created_at DESC)
	GetProductsByMerchant(ctx context.Context, arg GetProductsByMerchantParams) ([]*GetProductsByMerchantRow, error)
	// GetProductsTrashed: Retrieves paginated list of trashed (soft-deleted) products
	// Purpose: List deleted products for admin to manage recovery or audit
	// Parameters:
	//   $1: search_term - Optional text to filter trashed products (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All product fields plus total_count of matching trashed records
	// Business Logic:
	//   - Includes only soft-deleted products (deleted_at IS NOT NULL)
	//   - Supports partial, case-insensitive search on name, description, brand, slug, and barcode
	//   - Returns by newest first (created_at DESC)
	//   - Used for "Trash Bin" UI or soft-delete management
	GetProductsTrashed(ctx context.Context, arg GetProductsTrashedParams) ([]*GetProductsTrashedRow, error)
	// GetYearlyCategory: Retrieves annual sales performance for categories over a 5-year span
	// Purpose: Enables long-term product category performance trend analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	// Returns:
	//   year: 4-digit year as text
	//   category_id: Unique category identifier
	//   category_name: Display name of the category
	//   order_count: Annual number of orders involving this category
	//   items_sold: Quantity of products sold from this category
	//   total_revenue: Total sales revenue from category products
	//   unique_products_sold: Count of unique products sold within the category
	// Business Logic:
	//   - Covers the current year and previous four years (5-year window)
	//   - Filters out soft-deleted data from all related tables
	//   - Provides both volume and value metrics for category-level evaluation
	//   - Results sorted by year and revenue to show historical trends
	//   - Suitable for business reviews and strategic category planning
	GetYearlyCategory(ctx context.Context, dollar_1 time.Time) ([]*GetYearlyCategoryRow, error)
	// GetYearlyCategoryById: Retrieves annual sales performance for categories over a 5-year span by category_id
	// Purpose: Enables long-term product category performance trend analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	//   $2: Category ID
	// Returns:
	//   year: 4-digit year as text
	//   category_id: Unique category identifier
	//   category_name: Display name of the category
	//   order_count: Annual number of orders involving this category
	//   items_sold: Quantity of products sold from this category
	//   total_revenue: Total sales revenue from category products
	//   unique_products_sold: Count of unique products sold within the category
	// Business Logic:
	//   - Covers the current year and previous four years (5-year window)
	//   - Filters out soft-deleted data from all related tables
	//   - Provides both volume and value metrics for category-level evaluation
	//   - Results sorted by year and revenue to show historical trends
	//   - Suitable for business reviews and strategic category planning
	GetYearlyCategoryById(ctx context.Context, arg GetYearlyCategoryByIdParams) ([]*GetYearlyCategoryByIdRow, error)
	// GetYearlyCategoryByMerchant: Retrieves annual sales performance for categories over a 5-year span by merchant_id
	// Purpose: Enables long-term product category performance trend analysis
	// Parameters:
	//   $1: Reference date (timestamp) - determines the 5-year analysis window
	//   $2: Merchant ID
	// Returns:
	//   year: 4-digit year as text
	//   category_id: Unique category identifier
	//   category_name: Display name of the category
	//   order_count: Annual number of orders involving this category
	//   items_sold: Quantity of products sold from this category
	//   total_revenue: Total sales revenue from category products
	//   unique_products_sold: Count of unique products sold within the category
	// Business Logic:
	//   - Covers the current year and previous four years (5-year window)
	//   - Filters out soft-deleted data from all related tables
	//   - Provides both volume and value metrics for category-level evaluation
	//   - Results sorted by year and revenue to show historical trends
	//   - Suitable for business reviews and strategic category planning
	GetYearlyCategoryByMerchant(ctx context.Context, arg GetYearlyCategoryByMerchantParams) ([]*GetYearlyCategoryByMerchantRow, error)
	// GetYearlyTotalPrice: Retrieves annual revenue with category/product validation
	// Purpose: Provides year-over-year revenue analysis with product hierarchy verification
	// Parameters:
	//   $1: Reference year for comparison (current year)
	// Returns:
	//   year: Year as text
	//   total_revenue: Annual revenue total (0 if no sales)
	// Business Logic:
	//   - Compares current year with previous year automatically
	//   - Validates product/category relationships through joins
	//   - Excludes deleted records across all joined tables
	//   - Ensures complete year reporting even with no sales
	//   - Orders results by most recent year first
	GetYearlyTotalPrice(ctx context.Context, dollar_1 int32) ([]*GetYearlyTotalPriceRow, error)
	// GetYearlyTotalPriceById: Retrieves annual revenue with category/product validation by category_id
	// Purpose: Provides year-over-year revenue analysis with product hierarchy verification
	// Parameters:
	//   $1: Reference year for comparison (current year)
	//   $2: Category ID
	// Returns:
	//   year: Year as text
	//   total_revenue: Annual revenue total (0 if no sales)
	// Business Logic:
	//   - Compares current year with previous year automatically
	//   - Validates product/category relationships through joins
	//   - Excludes deleted records across all joined tables
	//   - Ensures complete year reporting even with no sales
	//   - Orders results by most recent year first
	GetYearlyTotalPriceById(ctx context.Context, arg GetYearlyTotalPriceByIdParams) ([]*GetYearlyTotalPriceByIdRow, error)
	// GetYearlyTotalPriceByMerchant: Retrieves annual revenue with category/product validation by merchant_id
	// Purpose: Provides year-over-year revenue analysis with product hierarchy verification
	// Parameters:
	//   $1: Reference year for comparison (current year)
	//   $2: Merchant ID
	// Returns:
	//   year: Year as text
	//   total_revenue: Annual revenue total (0 if no sales)
	// Business Logic:
	//   - Compares current year with previous year automatically
	//   - Validates product/category relationships through joins
	//   - Excludes deleted records across all joined tables
	//   - Ensures complete year reporting even with no sales
	//   - Orders results by most recent year first
	GetYearlyTotalPriceByMerchant(ctx context.Context, arg GetYearlyTotalPriceByMerchantParams) ([]*GetYearlyTotalPriceByMerchantRow, error)
	// IncrementProductCountStock: Atomically increments product stock
	// Purpose: Restore inventory after a compensated order operation
	// Parameters:
	//   $1: product_id - Product to update
	//   $2: quantity - Amount to add to current stock
	// Returns: Updated product record
	// Business Logic:
	//   - Atomic increment (no lost update between read and write)
	//   - Refuses non-positive quantities
	IncrementProductCountStock(ctx context.Context, arg IncrementProductCountStockParams) (*Product, error)
	// RestoreAllCategories: Recovers all trashed categories
	// Purpose: Bulk restore of all soft-deleted category records
	// Parameters: None
	// Returns: None
	// Business Logic:
	//   - Resets deleted_at for all soft-deleted records
	RestoreAllCategories(ctx context.Context) error
	// RestoreAllMerchants: Mass restoration of deleted merchants
	// Purpose: Recover all trashed merchants at once
	// Business Logic:
	//   - Reactivates all soft-deleted merchants
	//   - No parameters needed (bulk operation)
	//   - Typically used during system recovery
	//   - Maintains original merchant data
	RestoreAllMerchants(ctx context.Context) error
	// RestoreAllProducts: Mass restoration of deleted products
	// Purpose: Reactivate all trashed products
	// Business Logic:
	//   - Bulk restore operation
	//   - Used during data recovery
	RestoreAllProducts(ctx context.Context) error
	// RestoreCategory: Recovers a previously trashed category
	// Purpose: Restores a soft-deleted category for reuse
	// Parameters:
	//   $1: Category ID
	// Returns:
	//   Restored category record
	// Business Logic:
	//   - Only applies to categories currently marked as deleted
	RestoreCategory(ctx context.Context, categoryID int32) (*Category, error)
	// RestoreMerchant: Recovers a soft-deleted merchant
	// Purpose: Reactivate a previously deactivated merchant
	// Parameters:
	//   $1: merchant_id - ID of merchant to restore
	// Returns: The restored merchant record
	// Business Logic:
	//   - Nullifies the deleted_at field
	//   - Only works on previously deleted records
	//   - Preserves all original merchant data
	//   - Reactivates associated services
	RestoreMerchant(ctx context.Context, merchantID int32) (*Merchant, error)
	// RestoreProduct: Recovers a soft-deleted product
	// Purpose: Reactivate a removed product
	// Parameters:
	//   $1: product_id - Product to restore
	// Returns: The restored product
	// Business Logic:
	//   - Nullifies deleted_at
	//   - Returns product to active status
	RestoreProduct(ctx context.Context, productID int32) (*Product, error)
	// TrashCategory: Soft-deletes a category
	// Purpose: Moves category to trash without permanent deletion
	// Parameters:
	//   $1: Category ID
	// Returns:
	//   The soft-deleted category record
	// Business Logic:
	//   - Updates deleted_at with current timestamp
	//   - Prevents repeat trashing of already-deleted records
	TrashCategory(ctx context.Context, categoryID int32) (*Category, error)
	// TrashMerchant: Soft-deletes a merchant account
	// Purpose: Deactivate merchant without permanent deletion
	// Parameters:
	//   $1: merchant_id - ID of merchant to deactivate
	// Returns: The soft-deleted merchant record
	// Business Logic:
	//   - Sets deleted_at timestamp to current time
	//   - Only processes currently active records
	//   - Allows recovery via restore function
	//   - Maintains referential integrity
	TrashMerchant(ctx context.Context, merchantID int32) (*Merchant, error)
	// TrashProduct: Soft-deletes a product
	// Purpose: Remove product from active listings
	// Parameters:
	//   $1: product_id - Product to deactivate
	// Returns: The soft-deleted product
	// Business Logic:
	//   - Sets deleted_at timestamp
	//   - Preserves product data
	//   - Excludes from active queries
	TrashProduct(ctx context.Context, productID int32) (*Product, error)
	// UpdateCategory: Updates category details
	// Purpose: Modify existing category data while maintaining soft delete integrity
	// Parameters:
	//   $1: Category ID
	//   $2: Updated name
	//   $3: Updated description
	//   $4: Updated slug
	// Returns:
	//   Updated category record
	// Business Logic:
	//   - Automatically updates the updated_at field
	//   - Skips if category has been soft-deleted
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*Category, error)
	// UpdateMerchant: Modifies merchant information
	// Purpose: Update merchant profile details
	// Parameters:
	//   $1: merchant_id - Target merchant ID
	//   $2: name - Updated business name
	//   $3: description - Updated description
	//   $4: address - Updated physical address
	//   $5: contact_email - Updated email
	//   $6: contact_phone - Updated phone
	//   $7: status - Updated account status
	// Returns: Updated merchant record
	// Business Logic:
	//   - Automatically updates updated_at timestamp
	//   - Only affects active (non-deleted) records
	//   - Validates all required fields
	//   - Returns modified record for confirmation
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (*Merchant, error)
	UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (*Merchant, error)
	// UpdateProduct: Modifies product information
	// Purpose: Update product details
	// Parameters:
	//   $1: product_id - Target product ID
	//   $2: category_id - Updated category
	//   $3: name - Updated name
	//   $4: description - Updated description
	//   $5: price - Updated price
	//   $6: count_in_stock - Updated inventory count
	//   $7: brand - Updated brand
	//   $8: weight - Updated weight
	//   $9: image_product - Updated image
	//   $10: barcode - Updated barcode
	// Returns: Updated product record
	// Business Logic:
	//   - Auto-updates updated_at
	//   - Only modifies active products
	//   - Validates all fields
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (*Product, error)
	// UpdateProductCountStock: Updates inventory count
	// Purpose: Adjust product stock levels
	// Parameters:
	//   $1: product_id - Product to update
	//   $2: count_in_stock - New inventory count
	// Returns: Updated product record
	// Business Logic:
	//   - Dedicated stock adjustment function
	//   - Used when inventory changes
	//   - Validates non-negative quantity
	UpdateProductCountStock(ctx context.Context, arg UpdateProductCountStockParams) (*Product, error)
}

var _ Querier = (*Queries)(nil)
